//! Error-code enum generator for the TypeScript target.
//!
//! Port of `generateTypeScriptErrorEnum` from
//! `packages/protocol/src/generators/error-enums.ts`.
//!
//! Layout note: the TS source is a single module emitting all three
//! languages, but in this crate the Swift and Kotlin enum emitters live with
//! their artifact generators ([`crate::swift::generate_swift_error_enum`],
//! [`crate::kotlin::generate_kotlin_error_enum`]) because `artifacts.ts`
//! splices them into the Swift/Kotlin artifact files — the standalone
//! TypeScript error file is the only per-language error artifact the driver
//! writes on its own (`packages/core/src/generated/errors.ts`).
//!
//! The source of truth is [`FrickErrorCode::ALL`] (the Rust mirror of
//! `FRICK_ERROR_CODES` in `packages/protocol/src/errors.ts`); declaration
//! order matches the TS array, which is output-order significant.
//!
//! Returns the bare string (no trailing newline); the driver appends exactly
//! one `\n` when writing the artifact. Output is pinned byte-for-byte by
//! `conformance/fixtures/codegen/typescript/errors.ts` and the committed
//! artifact.

use frick_protocol::FrickErrorCode;

/// `generateTypeScriptErrorEnum()` — const array + derived union +
/// `ReadonlySet` + `isFrickErrorCode` guard.
#[must_use]
pub fn generate_typescript_error_enum() -> String {
    let items = FrickErrorCode::ALL
        .iter()
        .map(|code| format!("  {},", json_string(code.as_str())))
        .collect::<Vec<_>>()
        .join("\n");

    [
        "// Generated by @fricken/protocol from packages/protocol/src/errors.ts.",
        "// Do not edit by hand.",
        "export const FRICK_ERROR_CODES = [",
        items.as_str(),
        "] as const;",
        "export type FrickErrorCode = (typeof FRICK_ERROR_CODES)[number];",
        "export const FRICK_ERROR_CODE_SET: ReadonlySet<FrickErrorCode> = new Set(FRICK_ERROR_CODES);",
        "export function isFrickErrorCode(value: unknown): value is FrickErrorCode {",
        "  return typeof value === \"string\" && FRICK_ERROR_CODE_SET.has(value as FrickErrorCode);",
        "}",
    ]
    .join("\n")
}

/// `JSON.stringify` for a string value (same escaping as `serde_json` for
/// well-formed strings).
fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use super::generate_typescript_error_enum;
    use std::path::PathBuf;

    fn repo_file(rel: &str) -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(rel);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read {}: {err}", path.display()))
    }

    #[test]
    fn typescript_error_enum_matches_ts_fixture() {
        // Regenerate with:
        //   pnpm exec tsx packages/protocol/scripts/generate-codegen-fixtures-typescript.ts
        assert_eq!(
            format!("{}\n", generate_typescript_error_enum()),
            repo_file("conformance/fixtures/codegen/typescript/errors.ts")
        );
    }

    #[test]
    fn typescript_error_enum_matches_committed_artifact() {
        assert_eq!(
            format!("{}\n", generate_typescript_error_enum()),
            repo_file("packages/core/src/generated/errors.ts")
        );
    }

    /// The 16 wire codes, in `FRICK_ERROR_CODES` order, each JSON-quoted.
    #[test]
    fn emits_all_sixteen_codes_in_order() {
        let generated = generate_typescript_error_enum();
        let mut cursor = 0;
        for code in frick_protocol::FrickErrorCode::ALL {
            let entry = format!("  \"{}\",", code.as_str());
            let offset = generated[cursor..]
                .find(&entry)
                .unwrap_or_else(|| panic!("missing or out-of-order entry: {entry}"));
            cursor += offset + entry.len();
        }
    }
}
