//! Kotlin artifact generator.
//!
//! Ports the Kotlin half of `packages/protocol/src/artifacts.ts`
//! (`generateKotlinArtifact`) plus `generateKotlinErrorEnum` from
//! `packages/protocol/src/generators/error-enums.ts`. Output must be
//! byte-identical to the TypeScript generators for the same schema — pinned
//! by the golden fixtures under `conformance/fixtures/codegen/kotlin/`
//! (regenerate with
//! `pnpm exec tsx packages/protocol/scripts/generate-codegen-fixtures-kotlin.ts`)
//! and by the committed `pnpm schema:generate` artifact
//! `apps/android/frick/src/main/java/dev/frick/client/FrickGenerated.kt`
//! (which is the generator string plus one driver-appended trailing newline).
//!
//! Quirks carried over deliberately:
//!
//! - Object DTOs get an implicit first field
//!   `{ id: 0, name: "id", kind: "id", required: true }` unless a field named
//!   `id` (case-sensitive) is declared. The descriptor tables do **not**
//!   include it.
//! - Class names pass through `kotlinTypeName`, which only rewrites the
//!   substring `"RTC"` → `"Rtc"` (`WebRTCSignal` → `WebRtcSignalDto`).
//!   Property names pass through untouched (no keyword escaping — unlike
//!   Swift).
//! - `timestamp` maps to `String` (asymmetric with Swift's `Date`), and there
//!   is no `protocolVersion` constant.
//! - `sensitivity` and `mergePolicy` are server-only metadata and are never
//!   emitted.
//! - Empty descriptor tables keep the blank entry line (`mapOf(\n\n)`), and
//!   the `kotlinx.serialization.json.JsonElement` import appears only when an
//!   object/event/presence/signal/job field has `kind: "json"` (stream and
//!   presence/signal *key* fields are not consulted, matching TS).

use frick_protocol::FrickErrorCode;
use frick_protocol::schema::{FieldDef, FieldKind, FrickSchema};

/// `generateKotlinArtifact` in TS: the full `FrickGenerated.kt` body
/// (without the driver's trailing newline).
#[must_use]
pub fn generate_kotlin_artifact(schema: &FrickSchema) -> String {
    let mut lines: Vec<String> = vec![
        "// Generated by @fricken/protocol.".into(),
        "package dev.frick.client".into(),
    ];
    if schema_has_json_fields(schema) {
        lines.push(String::new());
        lines.push("import kotlinx.serialization.json.JsonElement".into());
    }
    lines.push(String::new());
    lines.push(format!(
        "const val FRICK_SCHEMA_ID: String = {}",
        json_quote(&schema.schema_id)
    ));
    lines.push(format!(
        "const val FRICK_SCHEMA_VERSION: String = {}",
        json_quote(&schema.schema_version)
    ));
    lines.push(format!(
        "const val FRICK_SCHEMA_REVISION: Int = {}",
        schema.schema_revision
    ));
    lines.push(format!(
        "const val FRICK_MINIMUM_CLIENT_REVISION: Int = {}",
        schema.minimum_client_revision
    ));
    lines.push(format!(
        "const val FRICK_MINIMUM_SERVER_REVISION: Int = {}",
        schema.minimum_server_revision
    ));
    lines.push(format!(
        "const val FRICK_SCHEMA_HASH: String = {}",
        json_quote(&schema.hash)
    ));
    lines.push(String::new());
    lines.push(kotlin_schema_descriptor(schema));
    lines.push(String::new());
    lines.push(generate_kotlin_error_enum());
    lines.push(String::new());

    for object in &schema.objects {
        lines.push(kotlin_class(
            &format!("{}Dto", kotlin_type_name(&object.name)),
            &object_fields(&object.fields),
        ));
    }
    for event in &schema.events {
        lines.push(kotlin_class(
            &format!("{}Dto", kotlin_type_name(&event.name)),
            &event.fields,
        ));
    }
    for presence in &schema.presences {
        lines.push(kotlin_class(
            &format!("{}Dto", kotlin_type_name(&presence.name)),
            &presence.fields,
        ));
    }
    for signal in &schema.signals {
        lines.push(kotlin_class(
            &format!("{}Dto", kotlin_type_name(&signal.name)),
            &signal.fields,
        ));
    }

    lines.join("\n")
}

/// `generateKotlinErrorEnum` in TS:
/// `enum class FrickErrorCode(val wireValue: String)` over the canonical
/// wire-code list, with a `fromWire` companion helper.
#[must_use]
pub fn generate_kotlin_error_enum() -> String {
    let cases = FrickErrorCode::ALL
        .iter()
        .map(|code| {
            format!(
                "  {}({}),",
                screaming_snake(code.as_str()),
                json_quote(code.as_str())
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let entry_map = FrickErrorCode::ALL
        .iter()
        .map(|code| {
            format!(
                "      {} to {},",
                json_quote(code.as_str()),
                screaming_snake(code.as_str())
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    [
        "/**",
        " * Stable error codes mirrored from `packages/protocol/src/errors.ts`.",
        " * Generated; do not edit by hand. Use [fromWire] to translate strings",
        " * arriving from the server, including future codes the client doesn't yet",
        " * know about (those round-trip as `null`).",
        " */",
        "enum class FrickErrorCode(val wireValue: String) {",
        &cases,
        "  ;",
        "  companion object {",
        "    private val BY_WIRE: Map<String, FrickErrorCode> = mapOf(",
        &entry_map,
        "    )",
        "    fun fromWire(value: String?): FrickErrorCode? = value?.let { BY_WIRE[it] }",
        "  }",
        "}",
    ]
    .join("\n")
}

/// `kotlinSchemaDescriptor` in TS — the five `internal val FRICK_*` tables.
fn kotlin_schema_descriptor(schema: &FrickSchema) -> String {
    let name_table = |entries: Vec<(i64, &String)>| {
        entries
            .into_iter()
            .map(|(id, name)| format!("  {id} to {},", json_quote(name)))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let field_table = |entries: Vec<(i64, &Vec<FieldDef>)>| {
        entries
            .into_iter()
            .map(|(id, fields)| {
                let pairs = fields
                    .iter()
                    .map(|field| format!("{} to {}", field.id, json_quote(&field.name)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("  {id} to mapOf({pairs}),")
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    let object_names = name_table(schema.objects.iter().map(|t| (t.id, &t.name)).collect());
    let stream_names = name_table(schema.streams.iter().map(|t| (t.id, &t.name)).collect());
    let event_names = name_table(schema.events.iter().map(|t| (t.id, &t.name)).collect());
    let object_field_entries =
        field_table(schema.objects.iter().map(|t| (t.id, &t.fields)).collect());
    let event_field_entries =
        field_table(schema.events.iter().map(|t| (t.id, &t.fields)).collect());

    [
        "/**",
        " * Type-id → name and (typeId → (fieldId → fieldName)) tables for the",
        " * foundation schema. Used by [FrickSyncSocket] to translate packed Delta",
        " * tuples (PackedObjectRecord / PackedStreamEvent) into named-field shapes",
        " * for consumers.",
        " */",
        "internal val FRICK_OBJECT_NAMES: Map<Int, String> = mapOf(",
        &object_names,
        ")",
        "internal val FRICK_STREAM_NAMES: Map<Int, String> = mapOf(",
        &stream_names,
        ")",
        "internal val FRICK_EVENT_NAMES: Map<Int, String> = mapOf(",
        &event_names,
        ")",
        "internal val FRICK_OBJECT_FIELDS: Map<Int, Map<Int, String>> = mapOf(",
        &object_field_entries,
        ")",
        "internal val FRICK_EVENT_FIELDS: Map<Int, Map<Int, String>> = mapOf(",
        &event_field_entries,
        ")",
    ]
    .join("\n")
}

/// `kotlinClass` in TS — one `data class {Name}Dto(…)` declaration. The
/// returned string ends with a newline (the TS array join's trailing `""`),
/// so consecutive declarations are blank-line separated when the caller
/// joins with `"\n"`.
fn kotlin_class(name: &str, fields: &[FieldDef]) -> String {
    let properties = fields
        .iter()
        .map(|field| {
            format!(
                "  val {}: {}{}",
                field.name,
                kotlin_type(field),
                if field.required { "" } else { " = null" }
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");

    format!("data class {name}(\n{properties}\n)\n")
}

/// `objectFields` in TS: prepend the implicit
/// `{ id: 0, name: "id", kind: "id", required: true }` field unless a field
/// named `id` (case-sensitive) is already declared.
fn object_fields(fields: &[FieldDef]) -> Vec<FieldDef> {
    if fields.iter().any(|field| field.name == "id") {
        return fields.to_vec();
    }
    let implicit_id = FieldDef {
        id: 0,
        name: "id".into(),
        kind: FieldKind::Id,
        required: true,
        ref_: None,
        enum_values: None,
        sensitivity: None,
    };
    let mut result = Vec::with_capacity(fields.len() + 1);
    result.push(implicit_id);
    result.extend(fields.iter().cloned());
    result
}

/// `kotlinType` in TS. Everything not special-cased — including `timestamp`
/// — maps to `String`; optional fields are nullable.
fn kotlin_type(field: &FieldDef) -> String {
    let base = match field.kind {
        FieldKind::Bool => "Boolean",
        FieldKind::Int => "Int",
        FieldKind::Bytes => "ByteArray",
        FieldKind::Json => "JsonElement",
        _ => "String",
    };
    if field.required {
        base.to_string()
    } else {
        format!("{base}?")
    }
}

/// `kotlinTypeName` in TS: `name.replaceAll("RTC", "Rtc")` and nothing else.
fn kotlin_type_name(name: &str) -> String {
    name.replace("RTC", "Rtc")
}

/// `schemaHasJsonFields` in TS — objects, events, presences, signals, and
/// jobs contribute their `fields`; key fields, blob metadata, and projection
/// fields do not.
fn schema_has_json_fields(schema: &FrickSchema) -> bool {
    let field_sets = schema
        .objects
        .iter()
        .map(|t| &t.fields)
        .chain(schema.events.iter().map(|t| &t.fields))
        .chain(schema.presences.iter().map(|t| &t.fields))
        .chain(schema.signals.iter().map(|t| &t.fields))
        .chain(schema.jobs.iter().map(|t| &t.fields));
    field_sets
        .flatten()
        .any(|field| field.kind == FieldKind::Json)
}

/// `screamingSnake` in error-enums.ts: split on `.`, per segment apply
/// `([a-z0-9])([A-Z]) → $1_$2` then uppercase, join with `_`
/// (`auth.sessionExpired` → `AUTH_SESSION_EXPIRED`).
fn screaming_snake(code: &str) -> String {
    code.split('.')
        .map(|segment| {
            let mut out = String::with_capacity(segment.len() + 4);
            let mut prev_lower_or_digit = false;
            for ch in segment.chars() {
                if prev_lower_or_digit && ch.is_ascii_uppercase() {
                    out.push('_');
                }
                prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
                out.push(ch.to_ascii_uppercase());
            }
            out
        })
        .collect::<Vec<_>>()
        .join("_")
}

/// `JSON.stringify` for a string value. serde_json escapes exactly the set
/// JSON.stringify does (`"`, `\`, control chars — short forms for
/// `\b \t \n \f \r`, lowercase `\u00xx` otherwise) and leaves non-ASCII
/// verbatim, so the bytes match for any valid UTF-8 input.
fn json_quote(text: &str) -> String {
    serde_json::to_string(text).expect("serializing a string to JSON cannot fail")
}

#[cfg(test)]
mod tests {
    use super::{generate_kotlin_artifact, generate_kotlin_error_enum, screaming_snake};
    use frick_protocol::{FrickFrame, FrickSchema, decode_frame, foundation_schema};
    use std::path::PathBuf;

    fn repo_file(relative: &str) -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(relative);
        std::fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!(
                "read {} (run `pnpm exec tsx packages/protocol/scripts/\
                 generate-codegen-fixtures-kotlin.ts` from the repo root first): {err}",
                path.display()
            )
        })
    }

    /// `productTestSchema` as the TS pipeline ships it: decoded from the
    /// validated golden wire fixture rather than re-transliterated here.
    fn product_test_schema() -> FrickSchema {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../conformance/fixtures/wire/schema-product-validated.bin");
        let bytes = std::fs::read(&path).unwrap_or_else(|err| {
            panic!(
                "read {} (run `pnpm fixtures:wire` first): {err}",
                path.display()
            )
        });
        let frame = decode_frame(&bytes).expect("fixture decodes as a frame");
        let FrickFrame::Schema(schema) = frame else {
            panic!("expected a Schema frame, got {frame:?}");
        };
        *schema
    }

    /// Byte-compare against the expected text line by line so a mismatch
    /// reports the first divergent line instead of two opaque blobs.
    fn assert_same_text(actual: &str, expected: &str, what: &str) {
        if actual == expected {
            return;
        }
        for (index, (actual_line, expected_line)) in
            actual.lines().zip(expected.lines()).enumerate()
        {
            assert_eq!(
                actual_line,
                expected_line,
                "{what}: first divergence at line {}",
                index + 1
            );
        }
        assert_eq!(
            actual.lines().count(),
            expected.lines().count(),
            "{what}: line counts differ"
        );
        // Same lines but different bytes — newline/EOF discipline.
        assert_eq!(
            actual, expected,
            "{what}: outputs differ only in line endings/EOF"
        );
    }

    #[test]
    fn kotlin_artifact_matches_foundation_fixture() {
        assert_same_text(
            &generate_kotlin_artifact(&foundation_schema()),
            &repo_file("conformance/fixtures/codegen/kotlin/foundation.kt"),
            "generateKotlinArtifact(foundationSchema)",
        );
    }

    #[test]
    fn kotlin_artifact_matches_product_test_fixture() {
        assert_same_text(
            &generate_kotlin_artifact(&product_test_schema()),
            &repo_file("conformance/fixtures/codegen/kotlin/product-test.kt"),
            "generateKotlinArtifact(productTestSchema)",
        );
    }

    #[test]
    fn kotlin_error_enum_matches_fixture() {
        assert_same_text(
            &generate_kotlin_error_enum(),
            &repo_file("conformance/fixtures/codegen/kotlin/error-enum.kt"),
            "generateKotlinErrorEnum()",
        );
    }

    /// The committed `pnpm schema:generate` artifact is the generator string
    /// plus the driver's single trailing newline
    /// (`generate-native-artifacts.ts` writes `` `${generateKotlinArtifact(foundationSchema)}\n` ``).
    #[test]
    fn kotlin_artifact_matches_committed_android_artifact() {
        let generated = format!("{}\n", generate_kotlin_artifact(&foundation_schema()));
        assert_same_text(
            &generated,
            &repo_file("apps/android/frick/src/main/java/dev/frick/client/FrickGenerated.kt"),
            "committed FrickGenerated.kt",
        );
    }

    #[test]
    fn screaming_snake_matches_ts_regex_semantics() {
        assert_eq!(
            screaming_snake("auth.sessionExpired"),
            "AUTH_SESSION_EXPIRED"
        );
        assert_eq!(screaming_snake("rateLimit.exceeded"), "RATE_LIMIT_EXCEEDED");
        assert_eq!(
            screaming_snake("blob.unsupportedContentType"),
            "BLOB_UNSUPPORTED_CONTENT_TYPE"
        );
        // Consecutive capitals do not get split (`([a-z0-9])([A-Z])` only
        // matches a lower/digit boundary): "aBC" → "A_BC".
        assert_eq!(screaming_snake("aBC"), "A_BC");
        assert_eq!(screaming_snake("v2Beta"), "V2_BETA");
    }
}
