//! Swift DTO + schema-descriptor generator.
//!
//! Ports the Swift half of `packages/protocol/src/artifacts.ts`
//! (`generateSwiftArtifact` and its helpers) plus `generateSwiftErrorEnum`
//! from `packages/protocol/src/generators/error-enums.ts`. The TS pipeline
//! never writes the Swift error enum to its own file — `generateSwiftArtifact`
//! imports it and embeds it directly in `FrickGenerated.swift` — so the port
//! lives here next to its only caller (the standalone
//! [`crate::error_enums`] module owns only the TypeScript error enum, the
//! one emitter with its own output file).
//!
//! Output must be byte-identical to the TS generator for the same schema.
//! Parity is pinned by the golden fixtures under
//! `conformance/fixtures/codegen/swift/` (regenerate with
//! `pnpm exec tsx packages/protocol/scripts/generate-codegen-fixtures-swift.ts`)
//! and by the committed artifact
//! `packages/swift/Sources/FrickSwift/Generated/FrickGenerated.swift`, which
//! the `pnpm schema:generate` driver writes as the generator output plus one
//! trailing newline.
//!
//! Faithfully-ported quirks worth knowing about:
//!
//! - Object DTOs get an implicit first field
//!   `{ id: 0, name: "id", kind: "id", required: true }` unless a declared
//!   field is already named `id` (case-sensitive match).
//! - The descriptor tables map *declared* fields only — the implicit `id`
//!   never appears there — and empty maps emit `[:]` because Swift parses
//!   `[]` as an array literal. An object with zero declared fields emits
//!   `id: [:]` via the TS `|| ":"` fallback.
//! - `FrickJSONValue` support is emitted only when an object/event/presence/
//!   signal/job **field** has `kind: "json"`; key fields, blob metadata
//!   fields, and projection fields are not consulted. The `FrickTimestamp`
//!   wrapper (for `timestamp` fields) is emitted under the same field-set rule,
//!   ahead of the `FrickJSONValue` block.
//! - `sensitivity` and `mergePolicy` are deliberately never emitted.

use frick_protocol::FrickErrorCode;
use frick_protocol::schema::{FieldDef, FieldKind, FrickSchema};

/// `generateSwiftArtifact` (artifacts.ts). Returns the artifact source
/// *without* a trailing newline; the generation driver appends exactly one
/// `\n` when writing the file.
#[must_use]
pub fn generate_swift_artifact(schema: &FrickSchema) -> String {
    let mut lines: Vec<String> = vec![
        "// Generated by @fricken/protocol.".into(),
        "import Foundation".into(),
        String::new(),
        "public enum FrickSchema {".into(),
        format!(
            "  public static let protocolVersion = {}",
            schema.protocol_version
        ),
        format!(
            "  public static let schemaId = {}",
            json_quote(&schema.schema_id)
        ),
        format!(
            "  public static let schemaVersion = {}",
            json_quote(&schema.schema_version)
        ),
        format!(
            "  public static let schemaRevision = {}",
            schema.schema_revision
        ),
        format!(
            "  public static let minimumClientRevision = {}",
            schema.minimum_client_revision
        ),
        format!(
            "  public static let minimumServerRevision = {}",
            schema.minimum_server_revision
        ),
        format!(
            "  public static let schemaHash = {}",
            json_quote(&schema.hash)
        ),
        "}".into(),
        String::new(),
        format!("public let frickSchemaHash = {}", json_quote(&schema.hash)),
        String::new(),
        swift_schema_descriptor(schema),
        String::new(),
        generate_swift_error_enum(),
        String::new(),
    ];

    if schema_has_timestamp_fields(schema) {
        lines.push(swift_timestamp_support().into());
        lines.push(String::new());
    }

    if schema_has_json_fields(schema) {
        lines.push(swift_json_value_support().into());
        lines.push(String::new());
    }

    for object in &schema.objects {
        lines.push(swift_struct(
            &format!("{}DTO", object.name),
            &object_fields(&object.fields),
            Some(&object.name),
        ));
    }
    for event in &schema.events {
        lines.push(swift_struct(
            &format!("{}DTO", event.name),
            &event.fields,
            None,
        ));
    }
    for presence in &schema.presences {
        lines.push(swift_struct(
            &format!("{}DTO", presence.name),
            &presence.fields,
            None,
        ));
    }
    for signal in &schema.signals {
        lines.push(swift_struct(
            &format!("{}DTO", signal.name),
            &signal.fields,
            None,
        ));
    }

    lines.join("\n")
}

/// `generateSwiftErrorEnum` (generators/error-enums.ts): the stable
/// error-code enum spliced into the artifact. Cases are camelized dotted
/// wire codes (`auth.sessionExpired` → `authSessionExpired`), in
/// `FRICK_ERROR_CODES` declaration order.
#[must_use]
pub fn generate_swift_error_enum() -> String {
    let cases = FrickErrorCode::ALL
        .iter()
        .map(|code| {
            format!(
                "  case {} = {}",
                camelize(code.as_str()),
                json_quote(code.as_str())
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    [
        "/// Stable error codes mirrored from `packages/protocol/src/errors.ts`.",
        "/// Generated; do not edit by hand. Decode wire strings via",
        "/// `FrickErrorCode(rawValue: ...)` — unknown future codes return `nil`",
        "/// so callers can fall back to a `.serverInternal` bucket.",
        "public enum FrickErrorCode: String, Codable, CaseIterable, Sendable {",
        &cases,
        "}",
    ]
    .join("\n")
}

/// `camelize` (generators/error-enums.ts): split a dotted wire code on `.`,
/// keep the first segment verbatim, and capitalize the first character of
/// every later segment.
fn camelize(code: &str) -> String {
    code.split('.')
        .enumerate()
        .map(|(index, segment)| {
            if index == 0 {
                segment.to_string()
            } else {
                let mut chars = segment.chars();
                chars.next().map_or_else(String::new, |first| {
                    first.to_uppercase().collect::<String>() + chars.as_str()
                })
            }
        })
        .collect()
}

/// `swiftSchemaDescriptor` (artifacts.ts): typeId → name and
/// typeId → (fieldId → fieldName) tables for objects, streams, and events
/// (presences/signals/projections are deliberately absent).
fn swift_schema_descriptor(schema: &FrickSchema) -> String {
    let object_names = dict_map(&schema.objects, |t| {
        format!("{}: {}", t.id, json_quote(&t.name))
    });
    let stream_names = dict_map(&schema.streams, |t| {
        format!("{}: {}", t.id, json_quote(&t.name))
    });
    let event_names = dict_map(&schema.events, |t| {
        format!("{}: {}", t.id, json_quote(&t.name))
    });
    let object_field_entries = dict_map(&schema.objects, |t| field_entry_map(t.id, &t.fields));
    let event_field_entries = dict_map(&schema.events, |t| field_entry_map(t.id, &t.fields));

    [
        "/// Type-id → name and (typeId → (fieldId → fieldName)) tables for the".to_string(),
        "/// foundation schema. Used by `FrickSyncSocket` to translate packed Delta".to_string(),
        "/// tuples (`PackedObjectRecord` / `PackedStreamEvent`) into named-field".to_string(),
        "/// shapes for consumers.".to_string(),
        "public enum FrickSchemaDescriptor {".to_string(),
        format!("  public static let objectNames: [Int: String] = {object_names}"),
        format!("  public static let streamNames: [Int: String] = {stream_names}"),
        format!("  public static let eventNames: [Int: String] = {event_names}"),
        format!("  public static let objectFields: [Int: [Int: String]] = {object_field_entries}"),
        format!("  public static let eventFields: [Int: [Int: String]] = {event_field_entries}"),
        "}".to_string(),
    ]
    .join("\n")
}

/// The `dictMap` closure in `swiftSchemaDescriptor`: Swift parses `[]` as an
/// empty *array* literal, so empty maps must emit `[:]`.
fn dict_map<T>(items: &[T], render: impl Fn(&T) -> String) -> String {
    if items.is_empty() {
        return "[:]".to_string();
    }
    let mut lines = vec!["[".to_string()];
    lines.extend(items.iter().map(|item| format!("    {},", render(item))));
    lines.push("  ]".to_string());
    lines.join("\n")
}

/// One `typeId: [fieldId: "name", …]` descriptor entry. A type with zero
/// declared fields renders `typeId: [:]` (the TS `|| ":"` fallback).
fn field_entry_map(type_id: i64, fields: &[FieldDef]) -> String {
    let entries = fields
        .iter()
        .map(|field| format!("{}: {}", field.id, json_quote(&field.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let entries = if entries.is_empty() {
        ":".to_string()
    } else {
        entries
    };
    format!("{type_id}: [{entries}]")
}

/// `swiftStruct` (artifacts.ts). `object_type_name` is `Some` for object
/// DTOs, which additionally conform to `Identifiable` and carry a
/// `frickType` constant.
fn swift_struct(name: &str, fields: &[FieldDef], object_type_name: Option<&str>) -> String {
    let properties = fields
        .iter()
        .map(|field| {
            format!(
                "  public var {}: {}",
                swift_identifier(&field.name),
                swift_type(field)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let parameters = fields
        .iter()
        .map(|field| {
            format!(
                "    {}: {}{}",
                swift_identifier(&field.name),
                swift_type(field),
                if field.required { "" } else { " = nil" }
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");
    let assignments = fields
        .iter()
        .map(|field| {
            let identifier = swift_identifier(&field.name);
            format!("    self.{identifier} = {identifier}")
        })
        .collect::<Vec<_>>()
        .join("\n");

    // Object DTOs carry a stable `id`, so conform to Identifiable and expose
    // a `frickType` constant (the schema object name) for callers that key
    // off it.
    let conformances = if object_type_name.is_some() {
        "Codable, Equatable, Sendable, Identifiable"
    } else {
        "Codable, Equatable, Sendable"
    };

    let mut lines = vec![format!("public struct {name}: {conformances} {{")];
    if let Some(type_name) = object_type_name {
        lines.push(format!(
            "  public static let frickType = {}",
            json_quote(type_name)
        ));
        lines.push(String::new());
    }
    lines.extend([
        properties,
        String::new(),
        "  public init(".to_string(),
        parameters,
        "  ) {".to_string(),
        assignments,
        "  }".to_string(),
        "}".to_string(),
        String::new(),
    ]);
    lines.join("\n")
}

/// `objectFields` (artifacts.ts): prepend the implicit
/// `{ id: 0, name: "id", kind: "id", required: true }` field unless a
/// declared field is already named `id`.
fn object_fields(fields: &[FieldDef]) -> Vec<FieldDef> {
    if fields.iter().any(|field| field.name == "id") {
        return fields.to_vec();
    }
    let implicit = FieldDef {
        id: 0,
        name: "id".to_string(),
        kind: FieldKind::Id,
        required: true,
        ref_: None,
        enum_values: None,
        sensitivity: None,
    };
    std::iter::once(implicit)
        .chain(fields.iter().cloned())
        .collect()
}

/// `swiftType` (artifacts.ts). `id`/`ref`/`string`/`enum` all map to
/// `String`; `timestamp` maps to the generated `FrickTimestamp` wrapper, which
/// carries the canonical RFC3339 wire string verbatim (re-encoding
/// byte-identically) while exposing a parsed `date`. Optional fields are made
/// nullable with `?`.
fn swift_type(field: &FieldDef) -> String {
    let base = match field.kind {
        FieldKind::Bool => "Bool",
        FieldKind::Int => "Int",
        FieldKind::Bytes => "Data",
        FieldKind::Json => "FrickJSONValue",
        FieldKind::Timestamp => "FrickTimestamp",
        FieldKind::Id | FieldKind::Ref | FieldKind::String | FieldKind::Enum => "String",
    };
    if field.required {
        base.to_string()
    } else {
        format!("{base}?")
    }
}

/// `swiftIdentifier` (artifacts.ts): backtick-escape the Swift keywords the
/// TS generator escapes — exactly `class`, `struct`, and `enum`.
fn swift_identifier(name: &str) -> String {
    if matches!(name, "class" | "struct" | "enum") {
        format!("`{name}`")
    } else {
        name.to_string()
    }
}

/// `schemaHasJsonFields` (artifacts.ts): only object/event/presence/signal/
/// job `fields` are consulted — never key fields, blob metadata fields, or
/// projection fields.
fn schema_has_json_fields(schema: &FrickSchema) -> bool {
    schema_has_field_kind(schema, FieldKind::Json)
}

/// `schemaHasTimestampFields` (artifacts.ts): same consulted field sets as
/// `schemaHasJsonFields`, gating emission of the `FrickTimestamp` wrapper.
fn schema_has_timestamp_fields(schema: &FrickSchema) -> bool {
    schema_has_field_kind(schema, FieldKind::Timestamp)
}

fn schema_has_field_kind(schema: &FrickSchema, kind: FieldKind) -> bool {
    schema
        .objects
        .iter()
        .map(|t| &t.fields)
        .chain(schema.events.iter().map(|t| &t.fields))
        .chain(schema.presences.iter().map(|t| &t.fields))
        .chain(schema.signals.iter().map(|t| &t.fields))
        .chain(schema.jobs.iter().map(|t| &t.fields))
        .flatten()
        .any(|field| field.kind == kind)
}

/// `swiftTimestampSupport` (artifacts.ts), verbatim.
const fn swift_timestamp_support() -> &'static str {
    r"/// An RFC3339 timestamp carried verbatim from the wire. The canonical
/// value is `rawValue` (a fixed RFC3339 string) — it re-encodes
/// byte-identically, so fractional seconds and the exact offset (`Z` vs
/// `+00:00`) never drift on round-trip. `date` is a lossy convenience that
/// parses `rawValue` into a `Date`; the wire value is unaffected by it, and
/// no app-level `JSONDecoder.dateDecodingStrategy` is required.
public struct FrickTimestamp: Codable, Equatable, Sendable {
  public let rawValue: String

  public init(_ rawValue: String) {
    self.rawValue = rawValue
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    self.rawValue = try container.decode(String.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(rawValue)
  }

  /// The parsed instant, or `nil` if `rawValue` is not a valid RFC3339
  /// timestamp. Parsing is millisecond-precision; `rawValue` keeps the full
  /// wire precision.
  public var date: Date? {
    let withFraction = ISO8601DateFormatter()
    withFraction.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    if let value = withFraction.date(from: rawValue) {
      return value
    }
    let withoutFraction = ISO8601DateFormatter()
    withoutFraction.formatOptions = [.withInternetDateTime]
    return withoutFraction.date(from: rawValue)
  }
}"
}

/// `swiftJsonValueSupport` (artifacts.ts), verbatim.
const fn swift_json_value_support() -> &'static str {
    r#"public indirect enum FrickJSONValue: Codable, Equatable, Sendable {
  case string(String)
  case int(Int)
  case double(Double)
  case bool(Bool)
  case array([FrickJSONValue])
  case object([String: FrickJSONValue])
  case null

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() {
      self = .null
    } else if let value = try? container.decode(String.self) {
      self = .string(value)
    } else if let value = try? container.decode(Int.self) {
      self = .int(value)
    } else if let value = try? container.decode(Double.self) {
      self = .double(value)
    } else if let value = try? container.decode(Bool.self) {
      self = .bool(value)
    } else if let value = try? container.decode([FrickJSONValue].self) {
      self = .array(value)
    } else if let value = try? container.decode([String: FrickJSONValue].self) {
      self = .object(value)
    } else {
      throw DecodingError.typeMismatch(
        FrickJSONValue.self,
        DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Unsupported JSON value")
      )
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .string(let value):
      try container.encode(value)
    case .int(let value):
      try container.encode(value)
    case .double(let value):
      try container.encode(value)
    case .bool(let value):
      try container.encode(value)
    case .array(let value):
      try container.encode(value)
    case .object(let value):
      try container.encode(value)
    case .null:
      try container.encodeNil()
    }
  }
}"#
}

/// `JSON.stringify` for strings: double-quoted with JSON escaping.
/// `serde_json` matches `JSON.stringify` byte-for-byte for valid UTF-8
/// (both escape `"` `\\` and control characters, and leave everything else
/// raw).
fn json_quote(text: &str) -> String {
    serde_json::to_string(text).expect("JSON string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use frick_protocol::schema::{
        BlobDef, EventDef, FieldDef, FieldKind, JobDef, ObjectDef, PresenceDef,
    };
    use frick_protocol::{FrickSchema, foundation_schema, validate_schema};

    use super::{camelize, generate_swift_artifact, generate_swift_error_enum};

    fn repo_path(relative: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(relative)
    }

    fn read_repo_file(relative: &str) -> String {
        let path = repo_path(relative);
        std::fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!(
                "read {} (run `pnpm exec tsx packages/protocol/scripts/generate-codegen-fixtures-swift.ts` first): {err}",
                path.display()
            )
        })
    }

    fn codegen_fixture(name: &str) -> String {
        read_repo_file(&format!("conformance/fixtures/codegen/swift/{name}"))
    }

    fn fixture_schema(name: &str) -> FrickSchema {
        let schema: FrickSchema =
            serde_json::from_str(&codegen_fixture(name)).expect("fixture schema deserializes");
        validate_schema(&schema).expect("fixture schema validates");
        schema
    }

    fn field(id: i64, name: &str, kind: FieldKind, required: bool) -> FieldDef {
        FieldDef {
            id,
            name: name.to_string(),
            kind,
            required,
            ref_: None,
            enum_values: None,
            sensitivity: None,
        }
    }

    fn enum_field(id: i64, name: &str, values: &[&str], required: bool) -> FieldDef {
        let mut def = field(id, name, FieldKind::Enum, required);
        def.enum_values = Some(values.iter().map(ToString::to_string).collect());
        def
    }

    /// The empty foundation skeleton with a synthetic identity, for tests
    /// that splice in hand-built types.
    fn synthetic_schema() -> FrickSchema {
        FrickSchema {
            name: "synthetic".to_string(),
            schema_id: "synthetic".to_string(),
            schema_version: "0.0.0".to_string(),
            hash: "synthetic-hash".to_string(),
            ..foundation_schema()
        }
    }

    #[test]
    fn foundation_artifact_matches_ts_fixture() {
        let generated = format!("{}\n", generate_swift_artifact(&foundation_schema()));
        assert_eq!(generated, codegen_fixture("foundation.swift"));
    }

    #[test]
    fn foundation_artifact_matches_committed_generated_file() {
        // The `pnpm schema:generate` driver writes the generator output plus
        // exactly one trailing newline, with no extra header or file
        // splitting — so the committed artifact is byte-identical to the
        // generator string + "\n".
        let generated = format!("{}\n", generate_swift_artifact(&foundation_schema()));
        let committed =
            read_repo_file("packages/swift/Sources/FrickSwift/Generated/FrickGenerated.swift");
        assert_eq!(generated, committed);
    }

    #[test]
    fn error_enum_matches_ts_fixture() {
        let generated = format!("{}\n", generate_swift_error_enum());
        assert_eq!(generated, codegen_fixture("error-enum.swift"));
    }

    #[test]
    fn camelize_matches_ts_semantics() {
        assert_eq!(camelize("auth.sessionExpired"), "authSessionExpired");
        assert_eq!(camelize("rateLimit.exceeded"), "rateLimitExceeded");
        assert_eq!(camelize("server.internal"), "serverInternal");
        // First segment is kept verbatim; only later segments capitalize.
        assert_eq!(camelize("a.b.c"), "aBC");
    }

    #[test]
    fn product_test_artifact_matches_ts_fixture() {
        let schema = fixture_schema("product-test-schema.json");
        let generated = format!("{}\n", generate_swift_artifact(&schema));
        assert_eq!(generated, codegen_fixture("product-test.swift"));
    }

    #[test]
    fn foundation_fixture_schema_round_trips_through_serde() {
        // The JSON fixture (validateSchema'd, key-sorted) must decode to the
        // same AST as the hand-written Rust foundation schema, so both test
        // inputs are interchangeable.
        assert_eq!(
            fixture_schema("foundation-schema.json"),
            foundation_schema()
        );
    }

    #[test]
    fn declared_id_field_suppresses_implicit_injection() {
        let mut schema = synthetic_schema();
        schema.objects = vec![ObjectDef {
            id: 1,
            name: "Widget".to_string(),
            fields: vec![
                field(1, "id", FieldKind::String, false),
                field(2, "label", FieldKind::String, true),
            ],
            indexes: vec![],
            merge_policy: None,
        }];
        let artifact = generate_swift_artifact(&schema);

        // The declared `id` keeps its own kind/optionality; no second `id`
        // property is injected.
        assert!(artifact.contains("  public var id: String?\n  public var label: String\n"));
        assert_eq!(artifact.matches("public var id").count(), 1);
    }

    #[test]
    fn object_without_id_field_gets_implicit_identifiable_id() {
        let mut schema = synthetic_schema();
        schema.objects = vec![ObjectDef {
            id: 1,
            name: "Widget".to_string(),
            fields: vec![field(1, "label", FieldKind::String, true)],
            indexes: vec![],
            merge_policy: None,
        }];
        let artifact = generate_swift_artifact(&schema);

        assert!(artifact.contains(
            "public struct WidgetDTO: Codable, Equatable, Sendable, Identifiable {\n  public static let frickType = \"Widget\"\n\n  public var id: String\n  public var label: String\n"
        ));
        // The descriptor maps declared fields only — no implicit id 0 entry.
        assert!(artifact.contains("1: [1: \"label\"],"));
    }

    #[test]
    fn zero_field_object_descriptor_entry_uses_empty_dictionary_literal() {
        let mut schema = synthetic_schema();
        schema.objects = vec![ObjectDef {
            id: 7,
            name: "Marker".to_string(),
            fields: vec![],
            indexes: vec![],
            merge_policy: None,
        }];
        let artifact = generate_swift_artifact(&schema);

        // The `|| ":"` fallback: zero declared fields renders `[:]`, not `[]`.
        assert!(artifact.contains("7: [:],"));
        // The DTO still gets the implicit id.
        assert!(artifact.contains("public struct MarkerDTO"));
        assert!(artifact.contains("  public var id: String\n"));
    }

    #[test]
    fn swift_keywords_are_backtick_escaped() {
        let mut schema = synthetic_schema();
        schema.events = vec![EventDef {
            id: 1,
            name: "Reserved".to_string(),
            fields: vec![
                field(1, "class", FieldKind::String, true),
                field(2, "struct", FieldKind::Int, false),
                enum_field(3, "enum", &["a"], true),
                field(4, "plain", FieldKind::Bool, true),
            ],
        }];
        let artifact = generate_swift_artifact(&schema);

        assert!(artifact.contains("  public var `class`: String\n"));
        assert!(artifact.contains("  public var `struct`: Int?\n"));
        assert!(artifact.contains("  public var `enum`: String\n"));
        assert!(artifact.contains("  public var plain: Bool\n"));
        assert!(artifact.contains("    `struct`: Int? = nil,\n"));
        assert!(artifact.contains("    self.`class` = `class`\n"));
    }

    #[test]
    fn json_field_in_jobs_emits_frick_json_value_support() {
        // Jobs get no DTO, but a json job field still flips the
        // FrickJSONValue emission switch.
        let mut schema = synthetic_schema();
        schema.jobs = vec![JobDef {
            id: 1,
            name: "SweepJob".to_string(),
            fields: vec![field(1, "payload", FieldKind::Json, true)],
        }];
        let artifact = generate_swift_artifact(&schema);
        assert!(artifact.contains("public indirect enum FrickJSONValue"));
    }

    #[test]
    fn timestamp_field_maps_to_wrapper_and_emits_support() {
        let mut schema = synthetic_schema();
        schema.events = vec![EventDef {
            id: 1,
            name: "Tick".to_string(),
            fields: vec![
                field(1, "at", FieldKind::Timestamp, true),
                field(2, "seenAt", FieldKind::Timestamp, false),
            ],
        }];
        let artifact = generate_swift_artifact(&schema);

        assert!(artifact.contains("public struct FrickTimestamp"));
        assert!(artifact.contains("  public var at: FrickTimestamp\n"));
        assert!(artifact.contains("  public var seenAt: FrickTimestamp?\n"));
        // No timestamp fields elsewhere means no JSON support gets dragged in.
        assert!(!artifact.contains("FrickJSONValue"));
    }

    #[test]
    fn timestamp_support_precedes_json_support() {
        // Both wrappers emit when both kinds are present; the timestamp block
        // is ahead of the JSON block (matches the TS generator ordering).
        let mut schema = synthetic_schema();
        schema.events = vec![EventDef {
            id: 1,
            name: "Mixed".to_string(),
            fields: vec![
                field(1, "at", FieldKind::Timestamp, true),
                field(2, "meta", FieldKind::Json, true),
            ],
        }];
        let artifact = generate_swift_artifact(&schema);

        let ts = artifact.find("public struct FrickTimestamp").unwrap();
        let json = artifact
            .find("public indirect enum FrickJSONValue")
            .unwrap();
        assert!(ts < json);
    }

    #[test]
    fn timestamp_outside_consulted_field_sets_does_not_emit_support() {
        // Presence/blob *key* and metadata fields are not consulted — mirror
        // the JSON omission rule for timestamps too.
        let mut schema = synthetic_schema();
        schema.presences = vec![PresenceDef {
            id: 1,
            name: "Ghost".to_string(),
            key_fields: vec![field(1, "since", FieldKind::Timestamp, true)],
            fields: vec![field(2, "alive", FieldKind::Bool, true)],
            ttl_ms: 1000,
        }];
        let artifact = generate_swift_artifact(&schema);
        assert!(!artifact.contains("FrickTimestamp"));
    }

    #[test]
    fn json_outside_consulted_field_sets_does_not_emit_support() {
        // Key fields and blob metadata fields are not consulted by
        // schemaHasJsonFields — mirror that omission exactly.
        let mut schema = synthetic_schema();
        schema.presences = vec![PresenceDef {
            id: 1,
            name: "Ghost".to_string(),
            key_fields: vec![field(1, "meta", FieldKind::Json, true)],
            fields: vec![field(2, "alive", FieldKind::Bool, true)],
            ttl_ms: 1000,
        }];
        schema.blobs = vec![BlobDef {
            id: 1,
            name: "RawBlob".to_string(),
            metadata_fields: vec![field(1, "extra", FieldKind::Json, false)],
        }];
        let artifact = generate_swift_artifact(&schema);
        assert!(!artifact.contains("FrickJSONValue"));
    }

    #[test]
    fn empty_schema_descriptor_maps_emit_swift_empty_dictionaries() {
        let artifact = generate_swift_artifact(&foundation_schema());
        assert!(artifact.contains("  public static let objectNames: [Int: String] = [:]\n"));
        assert!(artifact.contains("  public static let eventFields: [Int: [Int: String]] = [:]\n"));
    }
}
