//! Schema → TypeScript bindings generator.
//!
//! Port of `packages/protocol/src/generators/typescript.ts`
//! (`generateTypeScriptBindings`). Emits the single file consumed by
//! `@fricken/core` (`packages/core/src/generated/bindings.ts`):
//!
//! - One `interface XDto` per object / event / presence / signal (objects
//!   gain the implicit `id` field; enum kinds become string-literal unions).
//! - A `{Stream}Event` discriminated union per stream (`never` when empty).
//! - The typed `FrickBindings` interface plus the `bindFrickSchema` shim.
//! - `OBJECT_FIELD_INDEX` / `EVENT_FIELD_INDEX` field-id lookup tables.
//!
//! Pure `FrickSchema → String`, no I/O, no trailing newline — the driver
//! appends exactly one `\n` when writing the artifact. Output must be
//! byte-identical to the TS generator; pinned by the golden fixtures under
//! `conformance/fixtures/codegen/typescript/`.

use frick_protocol::schema::{FieldDef, FieldKind, FrickSchema};

/// Mirrors the TS generator's `options` bag
/// (`{ schemaImportPath?: string }`).
#[derive(Debug, Clone, Copy, Default)]
pub struct TypeScriptBindingsOptions<'a> {
    /// Overrides the `@fricken/protocol` import specifier
    /// (`options.schemaImportPath` in TS).
    pub schema_import_path: Option<&'a str>,
}

/// `generateTypeScriptBindings(schema)` with default options.
#[must_use]
pub fn generate_typescript_bindings(schema: &FrickSchema) -> String {
    generate_typescript_bindings_with_options(schema, TypeScriptBindingsOptions::default())
}

/// `generateTypeScriptBindings(schema, options)`.
#[must_use]
pub fn generate_typescript_bindings_with_options(
    schema: &FrickSchema,
    options: TypeScriptBindingsOptions<'_>,
) -> String {
    let import_path = options.schema_import_path.unwrap_or("@fricken/protocol");

    let mut declarations: Vec<String> = Vec::new();
    for object in &schema.objects {
        declarations.push(emit_dto(
            &format!("{}Dto", object.name),
            &with_id_field(&object.fields),
        ));
    }
    for event in &schema.events {
        declarations.push(emit_dto(&format!("{}Dto", event.name), &event.fields));
    }
    for presence in &schema.presences {
        declarations.push(emit_dto(&format!("{}Dto", presence.name), &presence.fields));
    }
    for signal in &schema.signals {
        declarations.push(emit_dto(&format!("{}Dto", signal.name), &signal.fields));
    }

    let mut stream_event_unions: Vec<String> = Vec::new();
    for stream in &schema.streams {
        let cases = if stream.events.is_empty() {
            "never".to_string()
        } else {
            stream
                .events
                .iter()
                .map(|event_name| {
                    format!(
                        "{{ event: {}; payload: {event_name}Dto }}",
                        json_string(event_name)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n  | ")
        };
        stream_event_unions.push(format!("export type {}Event =\n  | {cases};", stream.name));
    }

    let bindings_interface = bindings_interface(schema);

    let mut lines: Vec<String> = vec![
        "// Generated by @fricken/protocol. Do not edit by hand.".to_string(),
        format!(
            "// Source schema: {}@{} (hash={})",
            json_string(&schema.schema_id),
            schema.schema_version,
            json_string(&schema.hash)
        ),
        String::new(),
        "import type {".to_string(),
        "  ObjectBinding,".to_string(),
        "  StreamBinding,".to_string(),
        "  PresenceBinding,".to_string(),
        "  SignalBinding,".to_string(),
        "  ProjectionBinding,".to_string(),
        "} from \"../bindings.js\";".to_string(),
        "import { bindSchema } from \"../bindings.js\";".to_string(),
        "import type { FrickClient } from \"../runtime.js\";".to_string(),
        format!(
            "import {{ foundationSchema, type PlainObject }} from {};",
            json_string(import_path)
        ),
        String::new(),
        declarations.join("\n\n"),
        String::new(),
        stream_event_unions.join("\n\n"),
        String::new(),
        bindings_interface,
        String::new(),
        "/** Bind a client to the foundation schema and return the typed surface. */".to_string(),
        "export function bindFrickSchema(client: FrickClient): FrickBindings {".to_string(),
        "  return bindSchema(client, foundationSchema) as unknown as FrickBindings;".to_string(),
        "}".to_string(),
        String::new(),
        "/** Per-object field-id index, used at runtime to validate consumer calls. */".to_string(),
        "export const OBJECT_FIELD_INDEX = {".to_string(),
    ];
    for object in &schema.objects {
        lines.push(field_index_entry(
            &object.name,
            object.id,
            &with_id_field(&object.fields),
        ));
    }
    lines.push("} as const;".to_string());
    lines.push(String::new());
    lines.push("/** Per-event field-id index for typed appends. */".to_string());
    lines.push("export const EVENT_FIELD_INDEX = {".to_string());
    for event in &schema.events {
        lines.push(field_index_entry(&event.name, event.id, &event.fields));
    }
    lines.push("} as const;".to_string());

    lines.join("\n")
}

fn bindings_interface(schema: &FrickSchema) -> String {
    let mut lines: Vec<String> = vec![
        "/**".to_string(),
        " * Typed surface produced by `bindFrickSchema(client)`. Mirrors the schema".to_string(),
        " * one-to-one: every object, stream, presence, signal, and projection".to_string(),
        " * becomes a property with reactive accessors and mutation helpers.".to_string(),
        " */".to_string(),
        "export interface FrickBindings {".to_string(),
    ];
    lines.extend(
        schema
            .objects
            .iter()
            .map(|object| format!("  {0}: ObjectBinding<{0}Dto>;", object.name)),
    );
    lines.extend(
        schema
            .streams
            .iter()
            .map(|stream| format!("  {0}: StreamBinding<{0}Event>;", stream.name)),
    );
    lines.extend(
        schema
            .presences
            .iter()
            .map(|presence| format!("  {0}: PresenceBinding<{0}Dto>;", presence.name)),
    );
    lines.extend(
        schema
            .signals
            .iter()
            .map(|signal| format!("  {0}: SignalBinding<{0}Dto>;", signal.name)),
    );
    lines.extend(
        schema
            .projections
            .iter()
            .map(|projection| format!("  {}: ProjectionBinding<PlainObject>;", projection.name)),
    );
    lines.push("}".to_string());
    lines.join("\n")
}

/// One `  {Name}: { id: N, fields: { name: id, … } },` table row of
/// `OBJECT_FIELD_INDEX` / `EVENT_FIELD_INDEX`. An empty field list emits
/// `fields: {  }` (double space), matching the TS template literal.
fn field_index_entry(name: &str, id: i64, fields: &[FieldDef]) -> String {
    let entries = fields
        .iter()
        .map(|field| format!("{}: {}", quote_ident(&field.name), field.id))
        .collect::<Vec<_>>()
        .join(", ");
    format!("  {name}: {{ id: {id}, fields: {{ {entries} }} }},")
}

fn emit_dto(name: &str, fields: &[FieldDef]) -> String {
    let properties = fields
        .iter()
        .map(|field| {
            format!(
                "  {}{}: {};",
                field.name,
                if field.required { "" } else { "?" },
                ts_type(field)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("export interface {name} {{\n{properties}\n}}")
}

/// Object DTOs always carry an `id: string` even when the schema author
/// omits it (`withIdField` in TS; same implicit-id helper as Swift/Kotlin).
fn with_id_field(fields: &[FieldDef]) -> Vec<FieldDef> {
    if fields.iter().any(|field| field.name == "id") {
        return fields.to_vec();
    }
    let mut result = Vec::with_capacity(fields.len() + 1);
    result.push(FieldDef {
        id: 0,
        name: "id".to_string(),
        kind: FieldKind::Id,
        required: true,
        ref_: None,
        enum_values: None,
        sensitivity: None,
    });
    result.extend(fields.iter().cloned());
    result
}

fn ts_type(field: &FieldDef) -> String {
    match field.kind {
        FieldKind::Bool => "boolean".to_string(),
        FieldKind::Int => "number".to_string(),
        FieldKind::Bytes => "Uint8Array".to_string(),
        FieldKind::Json => "unknown".to_string(),
        FieldKind::Enum => match &field.enum_values {
            Some(values) if !values.is_empty() => values
                .iter()
                .map(|value| json_string(value))
                .collect::<Vec<_>>()
                .join(" | "),
            _ => "string".to_string(),
        },
        // id | ref | string | timestamp (and the TS `default` arm).
        FieldKind::Id | FieldKind::Ref | FieldKind::String | FieldKind::Timestamp => {
            "string".to_string()
        }
    }
}

/// `quoteIdent` in TS: bare when `/^[A-Za-z_$][A-Za-z0-9_$]*$/` matches,
/// JSON-quoted otherwise.
fn quote_ident(name: &str) -> String {
    let mut chars = name.chars();
    let is_ident = match chars.next() {
        Some(first) => {
            (first.is_ascii_alphabetic() || first == '_' || first == '$')
                && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        }
        None => false,
    };
    if is_ident {
        name.to_string()
    } else {
        json_string(name)
    }
}

/// `JSON.stringify` for a string value. `serde_json` escapes the identical
/// set (`"`/`\`, the C0 short escapes, `\u00XX` for the rest) for the
/// well-formed strings a Rust `String` can hold.
fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use super::{
        TypeScriptBindingsOptions, generate_typescript_bindings,
        generate_typescript_bindings_with_options, quote_ident,
    };
    use frick_protocol::{FrickFrame, FrickSchema, decode_frame, foundation_schema};
    use std::path::PathBuf;

    fn repo_file(rel: &str) -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(rel);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read {}: {err}", path.display()))
    }

    fn codegen_fixture(rel: &str) -> String {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../conformance/fixtures/codegen")
            .join(rel);
        std::fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!(
                "read {} (run `pnpm exec tsx \
                 packages/protocol/scripts/generate-codegen-fixtures-typescript.ts` \
                 first): {err}",
                path.display()
            )
        })
    }

    /// `productTestSchema`, decoded from the TS-encoded wire fixture so the
    /// input is exactly what `validateSchema(productTestSchema)` produced.
    fn product_test_schema() -> FrickSchema {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../conformance/fixtures/wire/schema-product-validated.bin");
        let bytes = std::fs::read(&path).unwrap_or_else(|err| {
            panic!(
                "read {} (run `pnpm fixtures:wire` first): {err}",
                path.display()
            )
        });
        let frame = decode_frame(&bytes).expect("fixture decodes as a frame");
        let FrickFrame::Schema(schema) = frame else {
            panic!("expected a Schema frame");
        };
        *schema
    }

    /// Byte-equality with a first-divergent-line report on failure, since a
    /// whole-file `assert_eq!` dump is unreadable.
    fn assert_bytes_identical(generated: &str, expected: &str) {
        if generated == expected {
            return;
        }
        for (index, (left, right)) in generated.lines().zip(expected.lines()).enumerate() {
            assert_eq!(left, right, "first divergence at line {}", index + 1);
        }
        panic!(
            "outputs share {} common lines but differ in length: generated {} bytes, expected {} bytes",
            generated.lines().count().min(expected.lines().count()),
            generated.len(),
            expected.len()
        );
    }

    #[test]
    fn foundation_bindings_match_ts_fixture() {
        let generated = format!("{}\n", generate_typescript_bindings(&foundation_schema()));
        assert_bytes_identical(
            &generated,
            &codegen_fixture("typescript/foundation-bindings.ts"),
        );
    }

    #[test]
    fn foundation_bindings_match_committed_artifact() {
        // The committed artifact is generated from the *raw* (unvalidated)
        // foundation literal by generate-native-artifacts.ts; content is
        // identical either way because the generator reads named fields.
        // The only pipeline-level difference is the driver's trailing "\n".
        let generated = format!("{}\n", generate_typescript_bindings(&foundation_schema()));
        assert_bytes_identical(
            &generated,
            &repo_file("packages/core/src/generated/bindings.ts"),
        );
    }

    #[test]
    fn product_test_bindings_match_ts_fixture() {
        let generated = format!("{}\n", generate_typescript_bindings(&product_test_schema()));
        assert_bytes_identical(
            &generated,
            &codegen_fixture("typescript/product-test-bindings.ts"),
        );
    }

    #[test]
    fn schema_import_path_option_is_json_quoted() {
        let generated = generate_typescript_bindings_with_options(
            &foundation_schema(),
            TypeScriptBindingsOptions {
                schema_import_path: Some("../protocol/index.js"),
            },
        );
        assert!(generated.contains(
            "import { foundationSchema, type PlainObject } from \"../protocol/index.js\";"
        ));
        assert!(!generated.contains("@fricken/protocol\";"));
    }

    #[test]
    fn quote_ident_matches_ts_regex() {
        assert_eq!(quote_ident("displayName"), "displayName");
        assert_eq!(quote_ident("_x$1"), "_x$1");
        assert_eq!(quote_ident("$"), "$");
        assert_eq!(quote_ident("1abc"), "\"1abc\"");
        assert_eq!(quote_ident("kebab-case"), "\"kebab-case\"");
        assert_eq!(quote_ident(""), "\"\"");
    }
}
