/**
 * Per-language emitter for the {@link FrickErrorCode} union. The TS source
 * of truth lives in `packages/protocol/src/errors.ts`; this generator emits:
 *
 *   - Swift: `public enum FrickErrorCode: String, Codable, CaseIterable, Sendable`
 *   - Kotlin: `enum class FrickErrorCode(val wireValue: String)` with a
 *     `fromWire(String?): FrickErrorCode?` helper for round-tripping
 *     wire strings that may include future codes.
 *
 * Returned as a single string with a trailing newline so the
 * `generate-native-artifacts.ts` driver can splice it directly into the
 * existing artifact files.
 */
import { FRICK_ERROR_CODES, type FrickErrorCode } from "../errors.js";

/**
 * Convert a dotted wire code like `"auth.sessionExpired"` into a Swift /
 * Kotlin identifier `"authSessionExpired"`. Stable across releases since the
 * wire codes themselves are stable.
 */
function camelize(code: FrickErrorCode): string {
  const segments = code.split(".");
  return segments
    .map((segment, index) =>
      index === 0 ? segment : segment.charAt(0).toUpperCase() + segment.slice(1),
    )
    .join("");
}

export function generateSwiftErrorEnum(): string {
  const cases = FRICK_ERROR_CODES.map(
    (code) => `  case ${camelize(code)} = ${JSON.stringify(code)}`,
  ).join("\n");

  return [
    "/// Stable error codes mirrored from `packages/protocol/src/errors.ts`.",
    "/// Generated; do not edit by hand. Decode wire strings via",
    "/// `FrickErrorCode(rawValue: ...)` — unknown future codes return `nil`",
    "/// so callers can fall back to a `.serverInternal` bucket.",
    "public enum FrickErrorCode: String, Codable, CaseIterable, Sendable {",
    cases,
    "}",
  ].join("\n");
}

/** Convert `"auth.sessionExpired"` → `"AUTH_SESSION_EXPIRED"`. */
function screamingSnake(code: FrickErrorCode): string {
  return code
    .split(".")
    .map((segment) => segment.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase())
    .join("_");
}

export function generateKotlinErrorEnum(): string {
  const cases = FRICK_ERROR_CODES.map(
    (code) => `  ${screamingSnake(code)}(${JSON.stringify(code)}),`,
  ).join("\n");
  const entryMap = FRICK_ERROR_CODES.map(
    (code) => `      ${JSON.stringify(code)} to ${screamingSnake(code)},`,
  ).join("\n");

  return [
    "/**",
    " * Stable error codes mirrored from `packages/protocol/src/errors.ts`.",
    " * Generated; do not edit by hand. Use [fromWire] to translate strings",
    " * arriving from the server, including future codes the client doesn't yet",
    " * know about (those round-trip as `null`).",
    " */",
    "enum class FrickErrorCode(val wireValue: String) {",
    cases,
    "  ;",
    "  companion object {",
    "    private val BY_WIRE: Map<String, FrickErrorCode> = mapOf(",
    entryMap,
    "    )",
    "    fun fromWire(value: String?): FrickErrorCode? = value?.let { BY_WIRE[it] }",
    "  }",
    "}",
  ].join("\n");
}

/**
 * Emit a TypeScript const-array + derived union plus a `Set` for
 * runtime membership checks. Mirrors the shape of the hand-written
 * `errors.ts` but lives at `packages/core/src/generated/errors.ts` so the
 * core package can import it without pulling in the protocol package's
 * type-only error file.
 */
export function generateTypeScriptErrorEnum(): string {
  const items = FRICK_ERROR_CODES.map((code) => `  ${JSON.stringify(code)},`).join("\n");
  return [
    "// Generated by @fricken/protocol from packages/protocol/src/errors.ts.",
    "// Do not edit by hand.",
    "export const FRICK_ERROR_CODES = [",
    items,
    "] as const;",
    "export type FrickErrorCode = (typeof FRICK_ERROR_CODES)[number];",
    "export const FRICK_ERROR_CODE_SET: ReadonlySet<FrickErrorCode> = new Set(FRICK_ERROR_CODES);",
    "export function isFrickErrorCode(value: unknown): value is FrickErrorCode {",
    "  return typeof value === \"string\" && FRICK_ERROR_CODE_SET.has(value as FrickErrorCode);",
    "}",
  ].join("\n");
}
