/**
 * Schema → TypeScript bindings generator.
 *
 * Emits a single file consumed by `@frick/core`:
 *
 *   - One `interface XDto` per object / event / presence / signal,
 *     mirroring the Swift / Kotlin DTOs but in TS shape (no JSON-as-string;
 *     enum kinds become string-literal unions).
 *   - Object/stream/event/presence/signal/projection name → field-map
 *     lookup tables (`OBJECT_FIELD_INDEX`, etc.) used at runtime by the
 *     hand-written `bindSchema(client, schema)` factory to validate
 *     consumer calls.
 *   - A typed `FrickBindings` interface keyed by schema name, surfacing
 *     `useAll`, `useOne`, `useStream`, `usePresence`, `useSignals`,
 *     `useProjection`, `append`, `upsert` accessors with the matching
 *     DTO types.
 *   - A factory shim `bindSchemaTyped(client) => FrickBindings` that
 *     delegates to the generic `bindSchema` and casts.
 *
 * Pure: `FrickSchema → string`. No I/O. The driver script
 * `scripts/generate-native-artifacts.ts` writes the output to
 * `packages/core/src/generated/bindings.ts`.
 */

import type { FieldDef, FrickSchema, ObjectDef, EventDef, PresenceDef, SignalDef, StreamDef } from "../schema.js";

export function generateTypeScriptBindings(schema: FrickSchema, options: { schemaImportPath?: string } = {}): string {
  const importPath = options.schemaImportPath ?? "@frick/protocol";
  const declarations: string[] = [];

  for (const object of schema.objects) {
    declarations.push(emitDto(`${object.name}Dto`, withIdField(object.fields)));
  }
  for (const event of schema.events) {
    declarations.push(emitDto(`${event.name}Dto`, event.fields));
  }
  for (const presence of schema.presences) {
    declarations.push(emitDto(`${presence.name}Dto`, presence.fields));
  }
  for (const signal of schema.signals) {
    declarations.push(emitDto(`${signal.name}Dto`, signal.fields));
  }

  const streamEventUnions: string[] = [];
  for (const stream of schema.streams) {
    const cases = stream.events.length === 0
      ? "never"
      : stream.events.map((eventName) => `{ event: ${JSON.stringify(eventName)}; payload: ${eventName}Dto }`).join("\n  | ");
    streamEventUnions.push(
      `export type ${stream.name}Event =\n  | ${cases};`,
    );
  }

  const objectsTable = schema.objects
    .map((object) => `  ${object.name}: { id: number; fields: { [K in keyof ${object.name}Dto]: number } }`)
    .join(";\n");

  const bindingsInterface = [
    "/**",
    " * Typed surface produced by `bindFrickSchema(client)`. Mirrors the schema",
    " * one-to-one: every object, stream, presence, signal, and projection",
    " * becomes a property with reactive accessors and mutation helpers.",
    " */",
    "export interface FrickBindings {",
    ...schema.objects.map((object) => `  ${object.name}: ObjectBinding<${object.name}Dto>;`),
    ...schema.streams.map((stream) => `  ${stream.name}: StreamBinding<${stream.name}Event>;`),
    ...schema.presences.map((presence) => `  ${presence.name}: PresenceBinding<${presence.name}Dto>;`),
    ...schema.signals.map((signal) => `  ${signal.name}: SignalBinding<${signal.name}Dto>;`),
    ...schema.projections.map((projection) => `  ${projection.name}: ProjectionBinding<PlainObject>;`),
    "}",
  ].join("\n");

  return [
    `// Generated by @frick/protocol. Do not edit by hand.`,
    `// Source schema: ${JSON.stringify(schema.schemaId)}@${schema.schemaVersion} (hash=${JSON.stringify(schema.hash)})`,
    ``,
    `import type {`,
    `  ObjectBinding,`,
    `  StreamBinding,`,
    `  PresenceBinding,`,
    `  SignalBinding,`,
    `  ProjectionBinding,`,
    `} from "../bindings.js";`,
    `import { bindSchema } from "../bindings.js";`,
    `import type { FrickClient } from "../runtime.js";`,
    `import { foundationSchema, type PlainObject } from ${JSON.stringify(importPath)};`,
    ``,
    declarations.join("\n\n"),
    ``,
    streamEventUnions.join("\n\n"),
    ``,
    bindingsInterface,
    ``,
    `/** Bind a client to the foundation schema and return the typed surface. */`,
    `export function bindFrickSchema(client: FrickClient): FrickBindings {`,
    `  return bindSchema(client, foundationSchema) as unknown as FrickBindings;`,
    `}`,
    ``,
    `/** Per-object field-id index, used at runtime to validate consumer calls. */`,
    `export const OBJECT_FIELD_INDEX = {`,
    ...schema.objects.map(
      (object) =>
        `  ${object.name}: { id: ${object.id}, fields: { ${withIdField(object.fields).map((f) => `${quoteIdent(f.name)}: ${f.id}`).join(", ")} } },`,
    ),
    `} as const;`,
    ``,
    `/** Per-event field-id index for typed appends. */`,
    `export const EVENT_FIELD_INDEX = {`,
    ...schema.events.map(
      (event) =>
        `  ${event.name}: { id: ${event.id}, fields: { ${event.fields.map((f) => `${quoteIdent(f.name)}: ${f.id}`).join(", ")} } },`,
    ),
    `} as const;`,
  ].join("\n");
}

function emitDto(name: string, fields: FieldDef[]): string {
  const properties = fields
    .map((field) => `  ${field.name}${field.required ? "" : "?"}: ${tsType(field)};`)
    .join("\n");
  return [`export interface ${name} {`, properties, `}`].join("\n");
}

/**
 * Object DTOs always carry an `id: string` even when the schema author omits
 * it. Mirrors the implicit-id helper in the Swift / Kotlin generators.
 */
function withIdField(fields: readonly FieldDef[]): FieldDef[] {
  if (fields.some((f) => f.name === "id")) return [...fields];
  return [{ id: 0, name: "id", kind: "id", required: true }, ...fields];
}

function tsType(field: FieldDef): string {
  switch (field.kind) {
    case "bool":
      return "boolean";
    case "int":
      return "number";
    case "bytes":
      return "Uint8Array";
    case "json":
      return "unknown";
    case "enum":
      return field.enumValues && field.enumValues.length > 0
        ? field.enumValues.map((value) => JSON.stringify(value)).join(" | ")
        : "string";
    case "id":
    case "ref":
    case "string":
    case "timestamp":
    default:
      return "string";
  }
}

function quoteIdent(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/**
 * Re-export the unused types so a downstream consumer that only imports
 * `FrickSchema` from this generator can still get `ObjectDef` etc.
 * (Not used directly; kept for ergonomics when extending the generator.)
 */
export type { FrickSchema, ObjectDef, EventDef, PresenceDef, SignalDef, StreamDef, FieldDef };
