//! `frick verify` — native drift gate for the generated codegen artifacts
//! (FR-263), replacing the TS command that shelled out to `pnpm
//! verify:generated`.
//!
//! The TS `frick verify` (`apps/cli/src/commands/verify.ts`) spawned `pnpm
//! verify:generated` (`scripts/check-generated-artifacts.ts`), which re-ran
//! `schema:generate` + `fixtures:generate` + `design:generate` and failed if any
//! tracked file went newly dirty. The Rust CLI reimplements the codegen slice of
//! that gate in-process: it runs [`frick_codegen`] for every target
//! (swift/kotlin/typescript) against the foundation schema and asserts the
//! generated bytes match the committed golden snapshots under
//! `conformance/fixtures/codegen/`. If regenerating any target would change the
//! tracked snapshot, the command fails with exit 1, naming the drifted target.
//!
//! What is covered vs the old `pnpm verify:generated`:
//!   - COVERED: the three native codegen targets (swift, kotlin, typescript),
//!     both the per-schema bindings/artifact and the error-enum, against the
//!     `conformance/fixtures/codegen/<target>/` golden files — exactly the
//!     snapshots the `frick-codegen` crate tests pin.
//!   - NOT COVERED (deferred): the `fixtures:generate` / `design:generate`
//!     stages, and the committed *consumer* artifacts in the package trees
//!     (`packages/swift/.../FrickGenerated.swift`, `packages/core/src/generated/
//!     *.ts`, `apps/android/.../FrickGenerated.kt`). Those are pinned by the
//!     `frick-codegen` crate's own committed-artifact tests; `frick verify` here
//!     checks the canonical golden snapshots, which the consumer artifacts are
//!     derived from (generator string + trailing "\n").

use std::path::{Path, PathBuf};

use frick_codegen::error_enums::generate_typescript_error_enum;
use frick_codegen::kotlin::{generate_kotlin_artifact, generate_kotlin_error_enum};
use frick_codegen::swift::{generate_swift_artifact, generate_swift_error_enum};
use frick_codegen::typescript::generate_typescript_bindings;
use frick_protocol::foundation_schema;
use serde_json::json;

use crate::argv::ParsedArgs;
use crate::errors::{CliError, EXIT_OK};
use crate::output::Output;

/// One generated artifact and the golden snapshot it must match.
struct Check {
    /// Codegen target this artifact belongs to (`swift`/`kotlin`/`typescript`).
    target: &'static str,
    /// Golden snapshot path, relative to the repo root.
    fixture: &'static str,
    /// The freshly generated bytes (already including the snapshot's trailing
    /// newline convention).
    generated: String,
}

/// The repo root the same way the `frick-codegen` tests resolve it
/// (`CARGO_MANIFEST_DIR/../..`), so `frick verify` reads the same golden files.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Build every (generated, golden-snapshot) pair the gate compares. The
/// trailing-newline handling mirrors each `frick-codegen` snapshot test:
/// swift/typescript snapshots are `generator + "\n"`; kotlin snapshots are the
/// raw generator string (it already ends in a newline).
fn checks() -> Vec<Check> {
    let schema = foundation_schema();
    vec![
        Check {
            target: "swift",
            fixture: "conformance/fixtures/codegen/swift/foundation.swift",
            generated: format!("{}\n", generate_swift_artifact(&schema)),
        },
        Check {
            target: "swift",
            fixture: "conformance/fixtures/codegen/swift/error-enum.swift",
            generated: format!("{}\n", generate_swift_error_enum()),
        },
        Check {
            target: "kotlin",
            fixture: "conformance/fixtures/codegen/kotlin/foundation.kt",
            generated: generate_kotlin_artifact(&schema),
        },
        Check {
            target: "kotlin",
            fixture: "conformance/fixtures/codegen/kotlin/error-enum.kt",
            generated: generate_kotlin_error_enum(),
        },
        Check {
            target: "typescript",
            fixture: "conformance/fixtures/codegen/typescript/foundation-bindings.ts",
            generated: format!("{}\n", generate_typescript_bindings(&schema)),
        },
        Check {
            target: "typescript",
            fixture: "conformance/fixtures/codegen/typescript/errors.ts",
            generated: format!("{}\n", generate_typescript_error_enum()),
        },
    ]
}

/// `verifyCommand` — run the native codegen drift gate against the repo-root
/// golden snapshots.
pub fn verify_command(_parsed: &ParsedArgs, out: &mut Output) -> Result<i32, CliError> {
    verify_with_fixture_root(&repo_root(), out)
}

/// The drift gate, parameterised by the fixture root the golden snapshots are
/// resolved against. The public [`verify_command`] passes the repo root; tests
/// point it at a temp tree to force drift deterministically without mutating the
/// committed fixtures.
pub fn verify_with_fixture_root(fixture_root: &Path, out: &mut Output) -> Result<i32, CliError> {
    let mut drift: Vec<serde_json::Value> = Vec::new();

    for check in checks() {
        let path = fixture_root.join(check.fixture);
        let expected = std::fs::read_to_string(&path).map_err(|err| {
            CliError::failure(
                "verify.fixtureMissing",
                format!(
                    "could not read golden snapshot {} \
                     (run `pnpm exec tsx packages/protocol/scripts/generate-codegen-fixtures-{}.ts` first): {err}",
                    path.display(),
                    check.target,
                ),
            )
        })?;

        if check.generated != expected {
            drift.push(json!({
                "target": check.target,
                "fixture": check.fixture,
                "line": first_divergent_line(&check.generated, &expected),
            }));
        }
    }

    let targets = ["swift", "kotlin", "typescript"];

    if drift.is_empty() {
        out.emit(&json!({
            "ok": true,
            "command": "frick verify (native)",
            "targets": targets,
        }));
        return Ok(EXIT_OK);
    }

    Err(CliError::failure_with(
        "verify.drift",
        "generated codegen output drifted from the committed snapshots; \
         re-run `frick schema generate` and commit the regenerated artifacts",
        json!({
            "command": "frick verify (native)",
            "targets": targets,
            "drift": drift,
        }),
    ))
}

/// Report the 1-based line of the first divergence between two texts (for the
/// drift detail), or `null` when one is a prefix of the other.
fn first_divergent_line(generated: &str, expected: &str) -> serde_json::Value {
    for (index, (left, right)) in generated.lines().zip(expected.lines()).enumerate() {
        if left != right {
            return json!(index + 1);
        }
    }
    serde_json::Value::Null
}
