import type { FieldDef, FrickSchema } from "./schema.js";

export function generateSwiftArtifact(schema: FrickSchema): string {
  const jsonSupport = schemaHasJsonFields(schema) ? [swiftJsonValueSupport(), ""] : [];
  const declarations = [
    ...schema.objects.map((type) => swiftStruct(`${type.name}DTO`, objectFields(type.fields))),
    ...schema.events.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
    ...schema.presences.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
    ...schema.signals.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
  ];

  return [
    "// Generated by @frick/protocol.",
    "import Foundation",
    "",
    "public enum FrickSchema {",
    `  public static let protocolVersion = ${schema.protocolVersion}`,
    `  public static let schemaId = ${JSON.stringify(schema.schemaId)}`,
    `  public static let schemaVersion = ${JSON.stringify(schema.schemaVersion)}`,
    `  public static let schemaRevision = ${schema.schemaRevision}`,
    `  public static let minimumClientRevision = ${schema.minimumClientRevision}`,
    `  public static let minimumServerRevision = ${schema.minimumServerRevision}`,
    `  public static let schemaHash = ${JSON.stringify(schema.hash)}`,
    "}",
    "",
    `public let frickSchemaHash = ${JSON.stringify(schema.hash)}`,
    "",
    ...jsonSupport,
    ...declarations,
  ].join("\n");
}

export function generateKotlinArtifact(schema: FrickSchema): string {
  const imports = schemaHasJsonFields(schema) ? ["", "import kotlinx.serialization.json.JsonElement"] : [];
  const declarations = [
    ...schema.objects.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, objectFields(type.fields))),
    ...schema.events.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
    ...schema.presences.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
    ...schema.signals.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
  ];

  return [
    "// Generated by @frick/protocol.",
    "package dev.frick.client",
    ...imports,
    "",
    `const val FRICK_SCHEMA_ID: String = ${JSON.stringify(schema.schemaId)}`,
    `const val FRICK_SCHEMA_VERSION: String = ${JSON.stringify(schema.schemaVersion)}`,
    `const val FRICK_SCHEMA_REVISION: Int = ${schema.schemaRevision}`,
    `const val FRICK_MINIMUM_CLIENT_REVISION: Int = ${schema.minimumClientRevision}`,
    `const val FRICK_MINIMUM_SERVER_REVISION: Int = ${schema.minimumServerRevision}`,
    `const val FRICK_SCHEMA_HASH: String = ${JSON.stringify(schema.hash)}`,
    "",
    ...declarations,
  ].join("\n");
}

function swiftStruct(name: string, fields: readonly FieldDef[]): string {
  const properties = fields
    .map((field) => `  public let ${swiftIdentifier(field.name)}: ${swiftType(field)}`)
    .join("\n");
  const parameters = fields
    .map((field) => `    ${swiftIdentifier(field.name)}: ${swiftType(field)}${field.required ? "" : " = nil"}`)
    .join(",\n");
  const assignments = fields
    .map((field) => `    self.${swiftIdentifier(field.name)} = ${swiftIdentifier(field.name)}`)
    .join("\n");

  return [
    `public struct ${name}: Codable, Equatable, Sendable {`,
    properties,
    "",
    "  public init(",
    parameters,
    "  ) {",
    assignments,
    "  }",
    "}",
    "",
  ].join("\n");
}

function kotlinClass(name: string, fields: readonly FieldDef[]): string {
  const properties = fields
    .map((field) => `  val ${field.name}: ${kotlinType(field)}${field.required ? "" : " = null"}`)
    .join(",\n");

  return [
    `data class ${name}(`,
    properties,
    ")",
    "",
  ].join("\n");
}

function objectFields(fields: readonly FieldDef[]): FieldDef[] {
  if (fields.some((field) => field.name === "id")) {
    return [...fields];
  }
  return [{ id: 0, name: "id", kind: "id", required: true }, ...fields];
}

function swiftType(field: FieldDef): string {
  const base =
    field.kind === "bool" ? "Bool"
      : field.kind === "int" ? "Int"
        : field.kind === "bytes" ? "Data"
          : field.kind === "json" ? "FrickJSONValue"
          : "String";
  return field.required ? base : `${base}?`;
}

function kotlinType(field: FieldDef): string {
  const base =
    field.kind === "bool" ? "Boolean"
      : field.kind === "int" ? "Int"
        : field.kind === "bytes" ? "ByteArray"
          : field.kind === "json" ? "JsonElement"
          : "String";
  return field.required ? base : `${base}?`;
}

function swiftIdentifier(name: string): string {
  return name === "class" || name === "struct" || name === "enum" ? `\`${name}\`` : name;
}

function kotlinTypeName(name: string): string {
  return name.replaceAll("RTC", "Rtc");
}

function schemaHasJsonFields(schema: FrickSchema): boolean {
  const fieldSets = [
    ...schema.objects.map((type) => type.fields),
    ...schema.events.map((type) => type.fields),
    ...schema.presences.map((type) => type.fields),
    ...schema.signals.map((type) => type.fields),
    ...schema.jobs.map((type) => type.fields),
  ];
  return fieldSets.some((fields) => fields.some((field) => field.kind === "json"));
}

function swiftJsonValueSupport(): string {
  return [
    "public indirect enum FrickJSONValue: Codable, Equatable, Sendable {",
    "  case string(String)",
    "  case int(Int)",
    "  case double(Double)",
    "  case bool(Bool)",
    "  case array([FrickJSONValue])",
    "  case object([String: FrickJSONValue])",
    "  case null",
    "",
    "  public init(from decoder: Decoder) throws {",
    "    let container = try decoder.singleValueContainer()",
    "    if container.decodeNil() {",
    "      self = .null",
    "    } else if let value = try? container.decode(String.self) {",
    "      self = .string(value)",
    "    } else if let value = try? container.decode(Int.self) {",
    "      self = .int(value)",
    "    } else if let value = try? container.decode(Double.self) {",
    "      self = .double(value)",
    "    } else if let value = try? container.decode(Bool.self) {",
    "      self = .bool(value)",
    "    } else if let value = try? container.decode([FrickJSONValue].self) {",
    "      self = .array(value)",
    "    } else if let value = try? container.decode([String: FrickJSONValue].self) {",
    "      self = .object(value)",
    "    } else {",
    "      throw DecodingError.typeMismatch(",
    "        FrickJSONValue.self,",
    "        DecodingError.Context(codingPath: decoder.codingPath, debugDescription: \"Unsupported JSON value\")",
    "      )",
    "    }",
    "  }",
    "",
    "  public func encode(to encoder: Encoder) throws {",
    "    var container = encoder.singleValueContainer()",
    "    switch self {",
    "    case .string(let value):",
    "      try container.encode(value)",
    "    case .int(let value):",
    "      try container.encode(value)",
    "    case .double(let value):",
    "      try container.encode(value)",
    "    case .bool(let value):",
    "      try container.encode(value)",
    "    case .array(let value):",
    "      try container.encode(value)",
    "    case .object(let value):",
    "      try container.encode(value)",
    "    case .null:",
    "      try container.encodeNil()",
    "    }",
    "  }",
    "}",
  ].join("\n");
}
