import type { FieldDef, FrickSchema } from "./schema.js";

export function generateSwiftArtifact(schema: FrickSchema): string {
  const declarations = [
    ...schema.objects.map((type) => swiftStruct(`${type.name}DTO`, objectFields(type.fields))),
    ...schema.events.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
    ...schema.presences.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
    ...schema.signals.map((type) => swiftStruct(`${type.name}DTO`, type.fields)),
  ];

  return [
    "// Generated by @frick/protocol.",
    "import Foundation",
    "",
    "public enum FrickSchema {",
    `  public static let protocolVersion = ${schema.protocolVersion}`,
    `  public static let schemaHash = ${JSON.stringify(schema.hash)}`,
    "}",
    "",
    `public let frickSchemaHash = ${JSON.stringify(schema.hash)}`,
    "",
    ...declarations,
  ].join("\n");
}

export function generateKotlinArtifact(schema: FrickSchema): string {
  const declarations = [
    ...schema.objects.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, objectFields(type.fields))),
    ...schema.events.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
    ...schema.presences.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
    ...schema.signals.map((type) => kotlinClass(`${kotlinTypeName(type.name)}Dto`, type.fields)),
  ];

  return [
    "// Generated by @frick/protocol.",
    "package dev.frick.client",
    "",
    `const val FRICK_SCHEMA_HASH: String = ${JSON.stringify(schema.hash)}`,
    "",
    ...declarations,
  ].join("\n");
}

function swiftStruct(name: string, fields: readonly FieldDef[]): string {
  const properties = fields
    .map((field) => `  public let ${swiftIdentifier(field.name)}: ${swiftType(field)}`)
    .join("\n");
  const parameters = fields
    .map((field) => `    ${swiftIdentifier(field.name)}: ${swiftType(field)}`)
    .join(",\n");
  const assignments = fields
    .map((field) => `    self.${swiftIdentifier(field.name)} = ${swiftIdentifier(field.name)}`)
    .join("\n");

  return [
    `public struct ${name}: Codable, Equatable, Sendable {`,
    properties,
    "",
    "  public init(",
    parameters,
    "  ) {",
    assignments,
    "  }",
    "}",
    "",
  ].join("\n");
}

function kotlinClass(name: string, fields: readonly FieldDef[]): string {
  const properties = fields
    .map((field) => `  val ${field.name}: ${kotlinType(field)}`)
    .join(",\n");

  return [
    `data class ${name}(`,
    properties,
    ")",
    "",
  ].join("\n");
}

function objectFields(fields: readonly FieldDef[]): FieldDef[] {
  if (fields.some((field) => field.name === "id")) {
    return [...fields];
  }
  return [{ id: 0, name: "id", kind: "id", required: true }, ...fields];
}

function swiftType(field: FieldDef): string {
  const base =
    field.kind === "bool" ? "Bool"
      : field.kind === "int" ? "Int"
        : field.kind === "bytes" ? "Data"
          : "String";
  return field.required ? base : `${base}?`;
}

function kotlinType(field: FieldDef): string {
  const base =
    field.kind === "bool" ? "Boolean"
      : field.kind === "int" ? "Int"
        : field.kind === "bytes" ? "ByteArray"
          : "String";
  return field.required ? base : `${base}?`;
}

function swiftIdentifier(name: string): string {
  return name === "class" || name === "struct" || name === "enum" ? `\`${name}\`` : name;
}

function kotlinTypeName(name: string): string {
  return name.replaceAll("RTC", "Rtc");
}
