// Generated by @fricken/protocol. Do not edit by hand.
// Source schema: "frick-product-test"@0.1.0 (hash="frick-product-test-0.2.0")

import type {
  ObjectBinding,
  StreamBinding,
  PresenceBinding,
  SignalBinding,
  ProjectionBinding,
} from "../bindings.js";
import { bindSchema } from "../bindings.js";
import type { FrickClient } from "../runtime.js";
import { foundationSchema, type PlainObject } from "@fricken/protocol";

export interface UserDto {
  id: string;
  displayName: string;
  avatarBlobId?: string;
}

export interface ConversationDto {
  id: string;
  kind: "dm" | "group" | "channel";
  title?: string;
  createdBy: string;
  lastMessageEventId?: string;
}

export interface RoomMemberDto {
  id: string;
  conversationId: string;
  userId: string;
  role: "owner" | "member";
}

export interface UserDeviceDto {
  id: string;
  userId: string;
  label?: string;
  platform: "web" | "ios" | "android" | "server";
  lastSeenAt?: string;
}

export interface UserSessionDto {
  id: string;
  userId: string;
  deviceId: string;
  replicaId: string;
  expiresAt: string;
}

export interface MessageDraftDto {
  id: string;
  userId: string;
  conversationId: string;
  body: string;
  updatedAt: string;
}

export interface ScheduledMessageDto {
  id: string;
  userId: string;
  conversationId: string;
  body: string;
  scheduledFor: string;
  attachmentBlobIds?: unknown;
  status: "pending" | "delivered" | "cancelled";
}

export interface CallRoomDto {
  id: string;
  conversationId: string;
  state: "ringing" | "active" | "ended";
  createdBy: string;
  kind: "audio" | "video";
  createdAt: string;
  startedAt?: string;
  endedAt?: string;
  mediaSessionId?: string;
  transport?: string;
}

export interface CallInviteDto {
  id: string;
  callId: string;
  inviteeUserId: string;
  status: "ringing" | "accepted" | "declined" | "cancelled";
  invitedBy: string;
  invitedAt: string;
  respondedAt?: string;
}

export interface CallParticipantDto {
  id: string;
  callId: string;
  userId: string;
  deviceId: string;
  state: "joined" | "left";
  joinedAt: string;
  leftAt?: string;
  micEnabled: boolean;
  cameraEnabled: boolean;
  screenSharing: boolean;
}

export interface MessageSentDto {
  messageId: string;
  senderId: string;
  body: string;
  createdAt: string;
  attachmentBlobIds?: unknown;
}

export interface MessageEditedDto {
  messageId: string;
  body: string;
  editedAt: string;
}

export interface MessageRedactedDto {
  messageId: string;
  redactedAt: string;
}

export interface ReactionAddedDto {
  messageId: string;
  userId: string;
  emoji: string;
}

export interface ReceiptAdvancedDto {
  userId: string;
  sequence: number;
}

export interface CallCreatedDto {
  callId: string;
  conversationId: string;
  createdBy: string;
  kind: string;
  createdAt: string;
}

export interface CallInviteSentDto {
  callId: string;
  inviteeUserId: string;
  invitedBy: string;
}

export interface CallInviteAcceptedDto {
  callId: string;
  inviteeUserId: string;
}

export interface CallParticipantJoinedDto {
  callId: string;
  userId: string;
  deviceId: string;
  joinedAt: string;
}

export interface CallParticipantMediaChangedDto {
  callId: string;
  userId: string;
  deviceId: string;
  micEnabled: boolean;
  cameraEnabled: boolean;
  screenSharing: boolean;
}

export interface CallParticipantLeftDto {
  callId: string;
  userId: string;
  deviceId: string;
  leftAt: string;
}

export interface CallEndedDto {
  callId: string;
  endedBy: string;
  endedAt: string;
}

export interface TypingStateDto {
  isTyping: boolean;
}

export interface WebRTCSignalDto {
  senderDeviceId: string;
  recipientDeviceId?: string;
  kind: "offer" | "answer" | "ice" | "renegotiate" | "sfuToken";
  payload: Uint8Array;
}

export type MessageStreamEvent =
  | { event: "MessageSent"; payload: MessageSentDto }
  | { event: "MessageEdited"; payload: MessageEditedDto }
  | { event: "MessageRedacted"; payload: MessageRedactedDto }
  | { event: "ReactionAdded"; payload: ReactionAddedDto }
  | { event: "ReceiptAdvanced"; payload: ReceiptAdvancedDto };

export type CallEventStreamEvent =
  | { event: "CallCreated"; payload: CallCreatedDto }
  | { event: "CallInviteSent"; payload: CallInviteSentDto }
  | { event: "CallInviteAccepted"; payload: CallInviteAcceptedDto }
  | { event: "CallParticipantJoined"; payload: CallParticipantJoinedDto }
  | { event: "CallParticipantMediaChanged"; payload: CallParticipantMediaChangedDto }
  | { event: "CallParticipantLeft"; payload: CallParticipantLeftDto }
  | { event: "CallEnded"; payload: CallEndedDto };

/**
 * Typed surface produced by `bindFrickSchema(client)`. Mirrors the schema
 * one-to-one: every object, stream, presence, signal, and projection
 * becomes a property with reactive accessors and mutation helpers.
 */
export interface FrickBindings {
  User: ObjectBinding<UserDto>;
  Conversation: ObjectBinding<ConversationDto>;
  RoomMember: ObjectBinding<RoomMemberDto>;
  UserDevice: ObjectBinding<UserDeviceDto>;
  UserSession: ObjectBinding<UserSessionDto>;
  MessageDraft: ObjectBinding<MessageDraftDto>;
  ScheduledMessage: ObjectBinding<ScheduledMessageDto>;
  CallRoom: ObjectBinding<CallRoomDto>;
  CallInvite: ObjectBinding<CallInviteDto>;
  CallParticipant: ObjectBinding<CallParticipantDto>;
  MessageStream: StreamBinding<MessageStreamEvent>;
  CallEventStream: StreamBinding<CallEventStreamEvent>;
  TypingState: PresenceBinding<TypingStateDto>;
  WebRTCSignal: SignalBinding<WebRTCSignalDto>;
  ConversationInbox: ProjectionBinding<PlainObject>;
}

/** Bind a client to the foundation schema and return the typed surface. */
export function bindFrickSchema(client: FrickClient): FrickBindings {
  return bindSchema(client, foundationSchema) as unknown as FrickBindings;
}

/** Per-object field-id index, used at runtime to validate consumer calls. */
export const OBJECT_FIELD_INDEX = {
  User: { id: 1, fields: { id: 0, displayName: 1, avatarBlobId: 2 } },
  Conversation: { id: 2, fields: { id: 0, kind: 1, title: 2, createdBy: 3, lastMessageEventId: 4 } },
  RoomMember: { id: 3, fields: { id: 0, conversationId: 1, userId: 2, role: 3 } },
  UserDevice: { id: 5, fields: { id: 0, userId: 1, label: 2, platform: 3, lastSeenAt: 4 } },
  UserSession: { id: 6, fields: { id: 0, userId: 1, deviceId: 2, replicaId: 3, expiresAt: 4 } },
  MessageDraft: { id: 7, fields: { id: 0, userId: 1, conversationId: 2, body: 3, updatedAt: 4 } },
  ScheduledMessage: { id: 8, fields: { id: 0, userId: 1, conversationId: 2, body: 3, scheduledFor: 4, attachmentBlobIds: 5, status: 6 } },
  CallRoom: { id: 9, fields: { id: 0, conversationId: 1, state: 2, createdBy: 3, kind: 4, createdAt: 5, startedAt: 6, endedAt: 7, mediaSessionId: 8, transport: 9 } },
  CallInvite: { id: 10, fields: { id: 0, callId: 1, inviteeUserId: 2, status: 3, invitedBy: 4, invitedAt: 5, respondedAt: 6 } },
  CallParticipant: { id: 11, fields: { id: 0, callId: 1, userId: 2, deviceId: 3, state: 4, joinedAt: 5, leftAt: 6, micEnabled: 7, cameraEnabled: 8, screenSharing: 9 } },
} as const;

/** Per-event field-id index for typed appends. */
export const EVENT_FIELD_INDEX = {
  MessageSent: { id: 1, fields: { messageId: 1, senderId: 2, body: 3, createdAt: 4, attachmentBlobIds: 5 } },
  MessageEdited: { id: 2, fields: { messageId: 1, body: 2, editedAt: 3 } },
  MessageRedacted: { id: 3, fields: { messageId: 1, redactedAt: 2 } },
  ReactionAdded: { id: 4, fields: { messageId: 1, userId: 2, emoji: 3 } },
  ReceiptAdvanced: { id: 5, fields: { userId: 1, sequence: 2 } },
  CallCreated: { id: 6, fields: { callId: 1, conversationId: 2, createdBy: 3, kind: 4, createdAt: 5 } },
  CallInviteSent: { id: 7, fields: { callId: 1, inviteeUserId: 2, invitedBy: 3 } },
  CallInviteAccepted: { id: 8, fields: { callId: 1, inviteeUserId: 2 } },
  CallParticipantJoined: { id: 9, fields: { callId: 1, userId: 2, deviceId: 3, joinedAt: 4 } },
  CallParticipantMediaChanged: { id: 10, fields: { callId: 1, userId: 2, deviceId: 3, micEnabled: 4, cameraEnabled: 5, screenSharing: 6 } },
  CallParticipantLeft: { id: 11, fields: { callId: 1, userId: 2, deviceId: 3, leftAt: 4 } },
  CallEnded: { id: 12, fields: { callId: 1, endedBy: 2, endedAt: 3 } },
} as const;
