// Generated by @frick/protocol.
package dev.frick.client

import kotlinx.serialization.json.JsonElement

const val FRICK_SCHEMA_ID: String = "frick-foundation"
const val FRICK_SCHEMA_VERSION: String = "0.1.0"
const val FRICK_SCHEMA_REVISION: Int = 1
const val FRICK_MINIMUM_CLIENT_REVISION: Int = 1
const val FRICK_MINIMUM_SERVER_REVISION: Int = 1
const val FRICK_SCHEMA_HASH: String = "frick-foundation-0.2.0"

/**
 * Type-id → name and (typeId → (fieldId → fieldName)) tables for the
 * foundation schema. Used by [FrickSyncSocket] to translate packed Delta
 * tuples (PackedObjectRecord / PackedStreamEvent) into named-field shapes
 * for consumers.
 */
internal val FRICK_OBJECT_NAMES: Map<Int, String> = mapOf(
  1 to "User",
  2 to "Conversation",
  3 to "RoomMember",
  4 to "CallRoom",
  5 to "UserDevice",
  6 to "UserSession",
  7 to "MessageDraft",
  8 to "ScheduledMessage",
)
internal val FRICK_STREAM_NAMES: Map<Int, String> = mapOf(
  1 to "MessageStream",
  2 to "CallEventStream",
)
internal val FRICK_EVENT_NAMES: Map<Int, String> = mapOf(
  1 to "MessageSent",
  2 to "MessageEdited",
  3 to "MessageRedacted",
  4 to "ReactionAdded",
  5 to "ReceiptAdvanced",
  6 to "CallCreated",
  7 to "CallParticipantJoined",
  8 to "CallParticipantLeft",
  9 to "CallEnded",
)
internal val FRICK_OBJECT_FIELDS: Map<Int, Map<Int, String>> = mapOf(
  1 to mapOf(1 to "displayName", 2 to "avatarBlobId"),
  2 to mapOf(1 to "kind", 2 to "title", 3 to "createdBy", 4 to "lastMessageEventId"),
  3 to mapOf(1 to "conversationId", 2 to "userId", 3 to "role"),
  4 to mapOf(1 to "conversationId", 2 to "state", 3 to "createdBy"),
  5 to mapOf(1 to "userId", 2 to "label", 3 to "platform", 4 to "lastSeenAt"),
  6 to mapOf(1 to "userId", 2 to "deviceId", 3 to "replicaId", 4 to "expiresAt"),
  7 to mapOf(1 to "userId", 2 to "conversationId", 3 to "body", 4 to "updatedAt"),
  8 to mapOf(1 to "userId", 2 to "conversationId", 3 to "body", 4 to "scheduledFor", 5 to "attachmentBlobIds", 6 to "status"),
)
internal val FRICK_EVENT_FIELDS: Map<Int, Map<Int, String>> = mapOf(
  1 to mapOf(1 to "messageId", 2 to "senderId", 3 to "body", 4 to "createdAt", 5 to "attachmentBlobIds"),
  2 to mapOf(1 to "messageId", 2 to "body", 3 to "editedAt"),
  3 to mapOf(1 to "messageId", 2 to "redactedAt"),
  4 to mapOf(1 to "messageId", 2 to "userId", 3 to "emoji"),
  5 to mapOf(1 to "userId", 2 to "sequence"),
  6 to mapOf(1 to "callId", 2 to "createdBy"),
  7 to mapOf(1 to "userId", 2 to "deviceId"),
  8 to mapOf(1 to "userId", 2 to "deviceId"),
  9 to mapOf(1 to "endedAt"),
)

/**
 * Stable error codes mirrored from `packages/protocol/src/errors.ts`.
 * Generated; do not edit by hand. Use [fromWire] to translate strings
 * arriving from the server, including future codes the client doesn't yet
 * know about (those round-trip as `null`).
 */
enum class FrickErrorCode(val wireValue: String) {
  AUTH_UNAUTHENTICATED("auth.unauthenticated"),
  AUTH_FORBIDDEN("auth.forbidden"),
  AUTH_SESSION_EXPIRED("auth.sessionExpired"),
  SCHEMA_INCOMPATIBLE("schema.incompatible"),
  SCHEMA_MIGRATION_REQUIRED("schema.migrationRequired"),
  STORAGE_CONFLICT("storage.conflict"),
  STORAGE_NOT_FOUND("storage.notFound"),
  STREAM_APPEND_REJECTED("stream.appendRejected"),
  SYNC_PROTOCOL_ERROR("sync.protocolError"),
  SYNC_RECONNECT_EXHAUSTED("sync.reconnectExhausted"),
  BLOB_TOO_LARGE("blob.tooLarge"),
  BLOB_UNSUPPORTED_CONTENT_TYPE("blob.unsupportedContentType"),
  RATE_LIMIT_EXCEEDED("rateLimit.exceeded"),
  SERVER_INTERNAL("server.internal"),
  ;
  companion object {
    private val BY_WIRE: Map<String, FrickErrorCode> = mapOf(
      "auth.unauthenticated" to AUTH_UNAUTHENTICATED,
      "auth.forbidden" to AUTH_FORBIDDEN,
      "auth.sessionExpired" to AUTH_SESSION_EXPIRED,
      "schema.incompatible" to SCHEMA_INCOMPATIBLE,
      "schema.migrationRequired" to SCHEMA_MIGRATION_REQUIRED,
      "storage.conflict" to STORAGE_CONFLICT,
      "storage.notFound" to STORAGE_NOT_FOUND,
      "stream.appendRejected" to STREAM_APPEND_REJECTED,
      "sync.protocolError" to SYNC_PROTOCOL_ERROR,
      "sync.reconnectExhausted" to SYNC_RECONNECT_EXHAUSTED,
      "blob.tooLarge" to BLOB_TOO_LARGE,
      "blob.unsupportedContentType" to BLOB_UNSUPPORTED_CONTENT_TYPE,
      "rateLimit.exceeded" to RATE_LIMIT_EXCEEDED,
      "server.internal" to SERVER_INTERNAL,
    )
    fun fromWire(value: String?): FrickErrorCode? = value?.let { BY_WIRE[it] }
  }
}

data class UserDto(
  val id: String,
  val displayName: String,
  val avatarBlobId: String? = null
)

data class ConversationDto(
  val id: String,
  val kind: String,
  val title: String? = null,
  val createdBy: String,
  val lastMessageEventId: String? = null
)

data class RoomMemberDto(
  val id: String,
  val conversationId: String,
  val userId: String,
  val role: String
)

data class CallRoomDto(
  val id: String,
  val conversationId: String,
  val state: String,
  val createdBy: String
)

data class UserDeviceDto(
  val id: String,
  val userId: String,
  val label: String? = null,
  val platform: String,
  val lastSeenAt: String? = null
)

data class UserSessionDto(
  val id: String,
  val userId: String,
  val deviceId: String,
  val replicaId: String,
  val expiresAt: String
)

data class MessageDraftDto(
  val id: String,
  val userId: String,
  val conversationId: String,
  val body: String,
  val updatedAt: String
)

data class ScheduledMessageDto(
  val id: String,
  val userId: String,
  val conversationId: String,
  val body: String,
  val scheduledFor: String,
  val attachmentBlobIds: JsonElement? = null,
  val status: String
)

data class MessageSentDto(
  val messageId: String,
  val senderId: String,
  val body: String,
  val createdAt: String,
  val attachmentBlobIds: JsonElement? = null
)

data class MessageEditedDto(
  val messageId: String,
  val body: String,
  val editedAt: String
)

data class MessageRedactedDto(
  val messageId: String,
  val redactedAt: String
)

data class ReactionAddedDto(
  val messageId: String,
  val userId: String,
  val emoji: String
)

data class ReceiptAdvancedDto(
  val userId: String,
  val sequence: Int
)

data class CallCreatedDto(
  val callId: String,
  val createdBy: String
)

data class CallParticipantJoinedDto(
  val userId: String,
  val deviceId: String
)

data class CallParticipantLeftDto(
  val userId: String,
  val deviceId: String
)

data class CallEndedDto(
  val endedAt: String
)

data class TypingStateDto(
  val isTyping: Boolean
)

data class WebRtcSignalDto(
  val senderDeviceId: String,
  val recipientDeviceId: String? = null,
  val kind: String,
  val payload: ByteArray
)

