// Generated by @frick/protocol.
package dev.frick.client

import kotlinx.serialization.json.JsonElement

const val FRICK_SCHEMA_ID: String = "frick-foundation"
const val FRICK_SCHEMA_VERSION: String = "0.1.0"
const val FRICK_SCHEMA_REVISION: Int = 1
const val FRICK_MINIMUM_CLIENT_REVISION: Int = 1
const val FRICK_MINIMUM_SERVER_REVISION: Int = 1
const val FRICK_SCHEMA_HASH: String = "frick-foundation-2026-05-09-dev-auth"

data class UserDto(
  val id: String,
  val displayName: String,
  val avatarBlobId: String? = null
)

data class ConversationDto(
  val id: String,
  val kind: String,
  val title: String? = null,
  val createdBy: String,
  val lastMessageEventId: String? = null
)

data class RoomMemberDto(
  val id: String,
  val conversationId: String,
  val userId: String,
  val role: String
)

data class CallRoomDto(
  val id: String,
  val conversationId: String,
  val state: String,
  val createdBy: String
)

data class UserDeviceDto(
  val id: String,
  val userId: String,
  val label: String? = null,
  val platform: String,
  val lastSeenAt: String? = null
)

data class UserSessionDto(
  val id: String,
  val userId: String,
  val deviceId: String,
  val replicaId: String,
  val expiresAt: String
)

data class MessageSentDto(
  val messageId: String,
  val senderId: String,
  val body: String,
  val createdAt: String,
  val attachmentBlobIds: JsonElement? = null
)

data class MessageEditedDto(
  val messageId: String,
  val body: String,
  val editedAt: String
)

data class MessageRedactedDto(
  val messageId: String,
  val redactedAt: String
)

data class ReactionAddedDto(
  val messageId: String,
  val userId: String,
  val emoji: String
)

data class ReceiptAdvancedDto(
  val userId: String,
  val sequence: Int
)

data class CallCreatedDto(
  val callId: String,
  val createdBy: String
)

data class CallParticipantJoinedDto(
  val userId: String,
  val deviceId: String
)

data class CallParticipantLeftDto(
  val userId: String,
  val deviceId: String
)

data class CallEndedDto(
  val endedAt: String
)

data class TypingStateDto(
  val isTyping: Boolean
)

data class WebRtcSignalDto(
  val senderDeviceId: String,
  val recipientDeviceId: String? = null,
  val kind: String,
  val payload: ByteArray
)

