// Generated by @frick/protocol.
package dev.frick.client

const val FRICK_SCHEMA_HASH: String = "frick-foundation-2026-05-09"

data class UserDto(
  val id: String,
  val displayName: String,
  val avatarBlobId: String?
)

data class ConversationDto(
  val id: String,
  val kind: String,
  val title: String?,
  val createdBy: String,
  val lastMessageEventId: String?
)

data class RoomMemberDto(
  val id: String,
  val conversationId: String,
  val userId: String,
  val role: String
)

data class CallRoomDto(
  val id: String,
  val conversationId: String,
  val state: String,
  val createdBy: String
)

data class MessageSentDto(
  val messageId: String,
  val senderId: String,
  val body: String,
  val createdAt: String
)

data class MessageEditedDto(
  val messageId: String,
  val body: String,
  val editedAt: String
)

data class MessageRedactedDto(
  val messageId: String,
  val redactedAt: String
)

data class ReactionAddedDto(
  val messageId: String,
  val userId: String,
  val emoji: String
)

data class ReceiptAdvancedDto(
  val userId: String,
  val sequence: Int
)

data class CallCreatedDto(
  val callId: String,
  val createdBy: String
)

data class CallParticipantJoinedDto(
  val userId: String,
  val deviceId: String
)

data class CallParticipantLeftDto(
  val userId: String,
  val deviceId: String
)

data class CallEndedDto(
  val endedAt: String
)

data class TypingStateDto(
  val isTyping: Boolean
)

data class WebRtcSignalDto(
  val senderDeviceId: String,
  val recipientDeviceId: String?,
  val kind: String,
  val payload: ByteArray
)

