// Generated by @fricken/protocol.
import Foundation

public enum FrickSchema {
  public static let protocolVersion = 1
  public static let schemaId = "frick-product-test"
  public static let schemaVersion = "0.1.0"
  public static let schemaRevision = 1
  public static let minimumClientRevision = 1
  public static let minimumServerRevision = 1
  public static let schemaHash = "frick-product-test-0.2.0"
}

public let frickSchemaHash = "frick-product-test-0.2.0"

/// Type-id → name and (typeId → (fieldId → fieldName)) tables for the
/// foundation schema. Used by `FrickSyncSocket` to translate packed Delta
/// tuples (`PackedObjectRecord` / `PackedStreamEvent`) into named-field
/// shapes for consumers.
public enum FrickSchemaDescriptor {
  public static let objectNames: [Int: String] = [
    1: "User",
    2: "Conversation",
    3: "RoomMember",
    5: "UserDevice",
    6: "UserSession",
    7: "MessageDraft",
    8: "ScheduledMessage",
    9: "CallRoom",
    10: "CallInvite",
    11: "CallParticipant",
  ]
  public static let streamNames: [Int: String] = [
    1: "MessageStream",
    2: "CallEventStream",
  ]
  public static let eventNames: [Int: String] = [
    1: "MessageSent",
    2: "MessageEdited",
    3: "MessageRedacted",
    4: "ReactionAdded",
    5: "ReceiptAdvanced",
    6: "CallCreated",
    7: "CallInviteSent",
    8: "CallInviteAccepted",
    9: "CallParticipantJoined",
    10: "CallParticipantMediaChanged",
    11: "CallParticipantLeft",
    12: "CallEnded",
  ]
  public static let objectFields: [Int: [Int: String]] = [
    1: [1: "displayName", 2: "avatarBlobId"],
    2: [1: "kind", 2: "title", 3: "createdBy", 4: "lastMessageEventId"],
    3: [1: "conversationId", 2: "userId", 3: "role"],
    5: [1: "userId", 2: "label", 3: "platform", 4: "lastSeenAt"],
    6: [1: "userId", 2: "deviceId", 3: "replicaId", 4: "expiresAt"],
    7: [1: "userId", 2: "conversationId", 3: "body", 4: "updatedAt"],
    8: [1: "userId", 2: "conversationId", 3: "body", 4: "scheduledFor", 5: "attachmentBlobIds", 6: "status"],
    9: [1: "conversationId", 2: "state", 3: "createdBy", 4: "kind", 5: "createdAt", 6: "startedAt", 7: "endedAt", 8: "mediaSessionId", 9: "transport"],
    10: [1: "callId", 2: "inviteeUserId", 3: "status", 4: "invitedBy", 5: "invitedAt", 6: "respondedAt"],
    11: [1: "callId", 2: "userId", 3: "deviceId", 4: "state", 5: "joinedAt", 6: "leftAt", 7: "micEnabled", 8: "cameraEnabled", 9: "screenSharing"],
  ]
  public static let eventFields: [Int: [Int: String]] = [
    1: [1: "messageId", 2: "senderId", 3: "body", 4: "createdAt", 5: "attachmentBlobIds"],
    2: [1: "messageId", 2: "body", 3: "editedAt"],
    3: [1: "messageId", 2: "redactedAt"],
    4: [1: "messageId", 2: "userId", 3: "emoji"],
    5: [1: "userId", 2: "sequence"],
    6: [1: "callId", 2: "conversationId", 3: "createdBy", 4: "kind", 5: "createdAt"],
    7: [1: "callId", 2: "inviteeUserId", 3: "invitedBy"],
    8: [1: "callId", 2: "inviteeUserId"],
    9: [1: "callId", 2: "userId", 3: "deviceId", 4: "joinedAt"],
    10: [1: "callId", 2: "userId", 3: "deviceId", 4: "micEnabled", 5: "cameraEnabled", 6: "screenSharing"],
    11: [1: "callId", 2: "userId", 3: "deviceId", 4: "leftAt"],
    12: [1: "callId", 2: "endedBy", 3: "endedAt"],
  ]
}

/// Stable error codes mirrored from `packages/protocol/src/errors.ts`.
/// Generated; do not edit by hand. Decode wire strings via
/// `FrickErrorCode(rawValue: ...)` — unknown future codes return `nil`
/// so callers can fall back to a `.serverInternal` bucket.
public enum FrickErrorCode: String, Codable, CaseIterable, Sendable {
  case authUnauthenticated = "auth.unauthenticated"
  case authForbidden = "auth.forbidden"
  case authSessionExpired = "auth.sessionExpired"
  case schemaIncompatible = "schema.incompatible"
  case schemaMigrationRequired = "schema.migrationRequired"
  case storageConflict = "storage.conflict"
  case storageNotFound = "storage.notFound"
  case streamAppendRejected = "stream.appendRejected"
  case streamInvalidCursor = "stream.invalidCursor"
  case syncProtocolError = "sync.protocolError"
  case syncReconnectExhausted = "sync.reconnectExhausted"
  case blobTooLarge = "blob.tooLarge"
  case blobUnsupportedContentType = "blob.unsupportedContentType"
  case blobQuotaExceeded = "blob.quotaExceeded"
  case rateLimitExceeded = "rateLimit.exceeded"
  case serverInternal = "server.internal"
}

public indirect enum FrickJSONValue: Codable, Equatable, Sendable {
  case string(String)
  case int(Int)
  case double(Double)
  case bool(Bool)
  case array([FrickJSONValue])
  case object([String: FrickJSONValue])
  case null

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() {
      self = .null
    } else if let value = try? container.decode(String.self) {
      self = .string(value)
    } else if let value = try? container.decode(Int.self) {
      self = .int(value)
    } else if let value = try? container.decode(Double.self) {
      self = .double(value)
    } else if let value = try? container.decode(Bool.self) {
      self = .bool(value)
    } else if let value = try? container.decode([FrickJSONValue].self) {
      self = .array(value)
    } else if let value = try? container.decode([String: FrickJSONValue].self) {
      self = .object(value)
    } else {
      throw DecodingError.typeMismatch(
        FrickJSONValue.self,
        DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Unsupported JSON value")
      )
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .string(let value):
      try container.encode(value)
    case .int(let value):
      try container.encode(value)
    case .double(let value):
      try container.encode(value)
    case .bool(let value):
      try container.encode(value)
    case .array(let value):
      try container.encode(value)
    case .object(let value):
      try container.encode(value)
    case .null:
      try container.encodeNil()
    }
  }
}

public struct UserDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "User"

  public var id: String
  public var displayName: String
  public var avatarBlobId: String?

  public init(
    id: String,
    displayName: String,
    avatarBlobId: String? = nil
  ) {
    self.id = id
    self.displayName = displayName
    self.avatarBlobId = avatarBlobId
  }
}

public struct ConversationDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "Conversation"

  public var id: String
  public var kind: String
  public var title: String?
  public var createdBy: String
  public var lastMessageEventId: String?

  public init(
    id: String,
    kind: String,
    title: String? = nil,
    createdBy: String,
    lastMessageEventId: String? = nil
  ) {
    self.id = id
    self.kind = kind
    self.title = title
    self.createdBy = createdBy
    self.lastMessageEventId = lastMessageEventId
  }
}

public struct RoomMemberDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "RoomMember"

  public var id: String
  public var conversationId: String
  public var userId: String
  public var role: String

  public init(
    id: String,
    conversationId: String,
    userId: String,
    role: String
  ) {
    self.id = id
    self.conversationId = conversationId
    self.userId = userId
    self.role = role
  }
}

public struct UserDeviceDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "UserDevice"

  public var id: String
  public var userId: String
  public var label: String?
  public var platform: String
  public var lastSeenAt: String?

  public init(
    id: String,
    userId: String,
    label: String? = nil,
    platform: String,
    lastSeenAt: String? = nil
  ) {
    self.id = id
    self.userId = userId
    self.label = label
    self.platform = platform
    self.lastSeenAt = lastSeenAt
  }
}

public struct UserSessionDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "UserSession"

  public var id: String
  public var userId: String
  public var deviceId: String
  public var replicaId: String
  public var expiresAt: String

  public init(
    id: String,
    userId: String,
    deviceId: String,
    replicaId: String,
    expiresAt: String
  ) {
    self.id = id
    self.userId = userId
    self.deviceId = deviceId
    self.replicaId = replicaId
    self.expiresAt = expiresAt
  }
}

public struct MessageDraftDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "MessageDraft"

  public var id: String
  public var userId: String
  public var conversationId: String
  public var body: String
  public var updatedAt: String

  public init(
    id: String,
    userId: String,
    conversationId: String,
    body: String,
    updatedAt: String
  ) {
    self.id = id
    self.userId = userId
    self.conversationId = conversationId
    self.body = body
    self.updatedAt = updatedAt
  }
}

public struct ScheduledMessageDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "ScheduledMessage"

  public var id: String
  public var userId: String
  public var conversationId: String
  public var body: String
  public var scheduledFor: String
  public var attachmentBlobIds: FrickJSONValue?
  public var status: String

  public init(
    id: String,
    userId: String,
    conversationId: String,
    body: String,
    scheduledFor: String,
    attachmentBlobIds: FrickJSONValue? = nil,
    status: String
  ) {
    self.id = id
    self.userId = userId
    self.conversationId = conversationId
    self.body = body
    self.scheduledFor = scheduledFor
    self.attachmentBlobIds = attachmentBlobIds
    self.status = status
  }
}

public struct CallRoomDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "CallRoom"

  public var id: String
  public var conversationId: String
  public var state: String
  public var createdBy: String
  public var kind: String
  public var createdAt: String
  public var startedAt: String?
  public var endedAt: String?
  public var mediaSessionId: String?
  public var transport: String?

  public init(
    id: String,
    conversationId: String,
    state: String,
    createdBy: String,
    kind: String,
    createdAt: String,
    startedAt: String? = nil,
    endedAt: String? = nil,
    mediaSessionId: String? = nil,
    transport: String? = nil
  ) {
    self.id = id
    self.conversationId = conversationId
    self.state = state
    self.createdBy = createdBy
    self.kind = kind
    self.createdAt = createdAt
    self.startedAt = startedAt
    self.endedAt = endedAt
    self.mediaSessionId = mediaSessionId
    self.transport = transport
  }
}

public struct CallInviteDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "CallInvite"

  public var id: String
  public var callId: String
  public var inviteeUserId: String
  public var status: String
  public var invitedBy: String
  public var invitedAt: String
  public var respondedAt: String?

  public init(
    id: String,
    callId: String,
    inviteeUserId: String,
    status: String,
    invitedBy: String,
    invitedAt: String,
    respondedAt: String? = nil
  ) {
    self.id = id
    self.callId = callId
    self.inviteeUserId = inviteeUserId
    self.status = status
    self.invitedBy = invitedBy
    self.invitedAt = invitedAt
    self.respondedAt = respondedAt
  }
}

public struct CallParticipantDTO: Codable, Equatable, Sendable, Identifiable {
  public static let frickType = "CallParticipant"

  public var id: String
  public var callId: String
  public var userId: String
  public var deviceId: String
  public var state: String
  public var joinedAt: String
  public var leftAt: String?
  public var micEnabled: Bool
  public var cameraEnabled: Bool
  public var screenSharing: Bool

  public init(
    id: String,
    callId: String,
    userId: String,
    deviceId: String,
    state: String,
    joinedAt: String,
    leftAt: String? = nil,
    micEnabled: Bool,
    cameraEnabled: Bool,
    screenSharing: Bool
  ) {
    self.id = id
    self.callId = callId
    self.userId = userId
    self.deviceId = deviceId
    self.state = state
    self.joinedAt = joinedAt
    self.leftAt = leftAt
    self.micEnabled = micEnabled
    self.cameraEnabled = cameraEnabled
    self.screenSharing = screenSharing
  }
}

public struct MessageSentDTO: Codable, Equatable, Sendable {
  public var messageId: String
  public var senderId: String
  public var body: String
  public var createdAt: String
  public var attachmentBlobIds: FrickJSONValue?

  public init(
    messageId: String,
    senderId: String,
    body: String,
    createdAt: String,
    attachmentBlobIds: FrickJSONValue? = nil
  ) {
    self.messageId = messageId
    self.senderId = senderId
    self.body = body
    self.createdAt = createdAt
    self.attachmentBlobIds = attachmentBlobIds
  }
}

public struct MessageEditedDTO: Codable, Equatable, Sendable {
  public var messageId: String
  public var body: String
  public var editedAt: String

  public init(
    messageId: String,
    body: String,
    editedAt: String
  ) {
    self.messageId = messageId
    self.body = body
    self.editedAt = editedAt
  }
}

public struct MessageRedactedDTO: Codable, Equatable, Sendable {
  public var messageId: String
  public var redactedAt: String

  public init(
    messageId: String,
    redactedAt: String
  ) {
    self.messageId = messageId
    self.redactedAt = redactedAt
  }
}

public struct ReactionAddedDTO: Codable, Equatable, Sendable {
  public var messageId: String
  public var userId: String
  public var emoji: String

  public init(
    messageId: String,
    userId: String,
    emoji: String
  ) {
    self.messageId = messageId
    self.userId = userId
    self.emoji = emoji
  }
}

public struct ReceiptAdvancedDTO: Codable, Equatable, Sendable {
  public var userId: String
  public var sequence: Int

  public init(
    userId: String,
    sequence: Int
  ) {
    self.userId = userId
    self.sequence = sequence
  }
}

public struct CallCreatedDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var conversationId: String
  public var createdBy: String
  public var kind: String
  public var createdAt: String

  public init(
    callId: String,
    conversationId: String,
    createdBy: String,
    kind: String,
    createdAt: String
  ) {
    self.callId = callId
    self.conversationId = conversationId
    self.createdBy = createdBy
    self.kind = kind
    self.createdAt = createdAt
  }
}

public struct CallInviteSentDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var inviteeUserId: String
  public var invitedBy: String

  public init(
    callId: String,
    inviteeUserId: String,
    invitedBy: String
  ) {
    self.callId = callId
    self.inviteeUserId = inviteeUserId
    self.invitedBy = invitedBy
  }
}

public struct CallInviteAcceptedDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var inviteeUserId: String

  public init(
    callId: String,
    inviteeUserId: String
  ) {
    self.callId = callId
    self.inviteeUserId = inviteeUserId
  }
}

public struct CallParticipantJoinedDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var userId: String
  public var deviceId: String
  public var joinedAt: String

  public init(
    callId: String,
    userId: String,
    deviceId: String,
    joinedAt: String
  ) {
    self.callId = callId
    self.userId = userId
    self.deviceId = deviceId
    self.joinedAt = joinedAt
  }
}

public struct CallParticipantMediaChangedDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var userId: String
  public var deviceId: String
  public var micEnabled: Bool
  public var cameraEnabled: Bool
  public var screenSharing: Bool

  public init(
    callId: String,
    userId: String,
    deviceId: String,
    micEnabled: Bool,
    cameraEnabled: Bool,
    screenSharing: Bool
  ) {
    self.callId = callId
    self.userId = userId
    self.deviceId = deviceId
    self.micEnabled = micEnabled
    self.cameraEnabled = cameraEnabled
    self.screenSharing = screenSharing
  }
}

public struct CallParticipantLeftDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var userId: String
  public var deviceId: String
  public var leftAt: String

  public init(
    callId: String,
    userId: String,
    deviceId: String,
    leftAt: String
  ) {
    self.callId = callId
    self.userId = userId
    self.deviceId = deviceId
    self.leftAt = leftAt
  }
}

public struct CallEndedDTO: Codable, Equatable, Sendable {
  public var callId: String
  public var endedBy: String
  public var endedAt: String

  public init(
    callId: String,
    endedBy: String,
    endedAt: String
  ) {
    self.callId = callId
    self.endedBy = endedBy
    self.endedAt = endedAt
  }
}

public struct TypingStateDTO: Codable, Equatable, Sendable {
  public var isTyping: Bool

  public init(
    isTyping: Bool
  ) {
    self.isTyping = isTyping
  }
}

public struct WebRTCSignalDTO: Codable, Equatable, Sendable {
  public var senderDeviceId: String
  public var recipientDeviceId: String?
  public var kind: String
  public var payload: Data

  public init(
    senderDeviceId: String,
    recipientDeviceId: String? = nil,
    kind: String,
    payload: Data
  ) {
    self.senderDeviceId = senderDeviceId
    self.recipientDeviceId = recipientDeviceId
    self.kind = kind
    self.payload = payload
  }
}

