// Generated by @fricken/protocol.
package dev.frick.client

import java.time.Instant
import java.time.OffsetDateTime
import java.time.format.DateTimeParseException
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

const val FRICK_SCHEMA_ID: String = "frick-product-test"
const val FRICK_SCHEMA_VERSION: String = "0.1.0"
const val FRICK_SCHEMA_REVISION: Int = 1
const val FRICK_MINIMUM_CLIENT_REVISION: Int = 1
const val FRICK_MINIMUM_SERVER_REVISION: Int = 1
const val FRICK_SCHEMA_HASH: String = "frick-product-test-0.2.0"

/**
 * Type-id → name and (typeId → (fieldId → fieldName)) tables for the
 * foundation schema. Used by [FrickSyncSocket] to translate packed Delta
 * tuples (PackedObjectRecord / PackedStreamEvent) into named-field shapes
 * for consumers.
 */
internal val FRICK_OBJECT_NAMES: Map<Int, String> = mapOf(
  1 to "User",
  2 to "Conversation",
  3 to "RoomMember",
  5 to "UserDevice",
  6 to "UserSession",
  7 to "MessageDraft",
  8 to "ScheduledMessage",
  9 to "CallRoom",
  10 to "CallInvite",
  11 to "CallParticipant",
)
internal val FRICK_STREAM_NAMES: Map<Int, String> = mapOf(
  1 to "MessageStream",
  2 to "CallEventStream",
)
internal val FRICK_EVENT_NAMES: Map<Int, String> = mapOf(
  1 to "MessageSent",
  2 to "MessageEdited",
  3 to "MessageRedacted",
  4 to "ReactionAdded",
  5 to "ReceiptAdvanced",
  6 to "CallCreated",
  7 to "CallInviteSent",
  8 to "CallInviteAccepted",
  9 to "CallParticipantJoined",
  10 to "CallParticipantMediaChanged",
  11 to "CallParticipantLeft",
  12 to "CallEnded",
)
internal val FRICK_OBJECT_FIELDS: Map<Int, Map<Int, String>> = mapOf(
  1 to mapOf(1 to "displayName", 2 to "avatarBlobId"),
  2 to mapOf(1 to "kind", 2 to "title", 3 to "createdBy", 4 to "lastMessageEventId"),
  3 to mapOf(1 to "conversationId", 2 to "userId", 3 to "role"),
  5 to mapOf(1 to "userId", 2 to "label", 3 to "platform", 4 to "lastSeenAt"),
  6 to mapOf(1 to "userId", 2 to "deviceId", 3 to "replicaId", 4 to "expiresAt"),
  7 to mapOf(1 to "userId", 2 to "conversationId", 3 to "body", 4 to "updatedAt"),
  8 to mapOf(1 to "userId", 2 to "conversationId", 3 to "body", 4 to "scheduledFor", 5 to "attachmentBlobIds", 6 to "status"),
  9 to mapOf(1 to "conversationId", 2 to "state", 3 to "createdBy", 4 to "kind", 5 to "createdAt", 6 to "startedAt", 7 to "endedAt", 8 to "mediaSessionId", 9 to "transport"),
  10 to mapOf(1 to "callId", 2 to "inviteeUserId", 3 to "status", 4 to "invitedBy", 5 to "invitedAt", 6 to "respondedAt"),
  11 to mapOf(1 to "callId", 2 to "userId", 3 to "deviceId", 4 to "state", 5 to "joinedAt", 6 to "leftAt", 7 to "micEnabled", 8 to "cameraEnabled", 9 to "screenSharing"),
)
internal val FRICK_EVENT_FIELDS: Map<Int, Map<Int, String>> = mapOf(
  1 to mapOf(1 to "messageId", 2 to "senderId", 3 to "body", 4 to "createdAt", 5 to "attachmentBlobIds"),
  2 to mapOf(1 to "messageId", 2 to "body", 3 to "editedAt"),
  3 to mapOf(1 to "messageId", 2 to "redactedAt"),
  4 to mapOf(1 to "messageId", 2 to "userId", 3 to "emoji"),
  5 to mapOf(1 to "userId", 2 to "sequence"),
  6 to mapOf(1 to "callId", 2 to "conversationId", 3 to "createdBy", 4 to "kind", 5 to "createdAt"),
  7 to mapOf(1 to "callId", 2 to "inviteeUserId", 3 to "invitedBy"),
  8 to mapOf(1 to "callId", 2 to "inviteeUserId"),
  9 to mapOf(1 to "callId", 2 to "userId", 3 to "deviceId", 4 to "joinedAt"),
  10 to mapOf(1 to "callId", 2 to "userId", 3 to "deviceId", 4 to "micEnabled", 5 to "cameraEnabled", 6 to "screenSharing"),
  11 to mapOf(1 to "callId", 2 to "userId", 3 to "deviceId", 4 to "leftAt"),
  12 to mapOf(1 to "callId", 2 to "endedBy", 3 to "endedAt"),
)

/**
 * Stable error codes mirrored from `packages/protocol/src/errors.ts`.
 * Generated; do not edit by hand. Use [fromWire] to translate strings
 * arriving from the server, including future codes the client doesn't yet
 * know about (those round-trip as `null`).
 */
enum class FrickErrorCode(val wireValue: String) {
  AUTH_UNAUTHENTICATED("auth.unauthenticated"),
  AUTH_FORBIDDEN("auth.forbidden"),
  AUTH_SESSION_EXPIRED("auth.sessionExpired"),
  SCHEMA_INCOMPATIBLE("schema.incompatible"),
  SCHEMA_MIGRATION_REQUIRED("schema.migrationRequired"),
  STORAGE_CONFLICT("storage.conflict"),
  STORAGE_NOT_FOUND("storage.notFound"),
  STREAM_APPEND_REJECTED("stream.appendRejected"),
  STREAM_INVALID_CURSOR("stream.invalidCursor"),
  SYNC_PROTOCOL_ERROR("sync.protocolError"),
  SYNC_RECONNECT_EXHAUSTED("sync.reconnectExhausted"),
  BLOB_TOO_LARGE("blob.tooLarge"),
  BLOB_UNSUPPORTED_CONTENT_TYPE("blob.unsupportedContentType"),
  BLOB_QUOTA_EXCEEDED("blob.quotaExceeded"),
  RATE_LIMIT_EXCEEDED("rateLimit.exceeded"),
  SERVER_INTERNAL("server.internal"),
  ;
  companion object {
    private val BY_WIRE: Map<String, FrickErrorCode> = mapOf(
      "auth.unauthenticated" to AUTH_UNAUTHENTICATED,
      "auth.forbidden" to AUTH_FORBIDDEN,
      "auth.sessionExpired" to AUTH_SESSION_EXPIRED,
      "schema.incompatible" to SCHEMA_INCOMPATIBLE,
      "schema.migrationRequired" to SCHEMA_MIGRATION_REQUIRED,
      "storage.conflict" to STORAGE_CONFLICT,
      "storage.notFound" to STORAGE_NOT_FOUND,
      "stream.appendRejected" to STREAM_APPEND_REJECTED,
      "stream.invalidCursor" to STREAM_INVALID_CURSOR,
      "sync.protocolError" to SYNC_PROTOCOL_ERROR,
      "sync.reconnectExhausted" to SYNC_RECONNECT_EXHAUSTED,
      "blob.tooLarge" to BLOB_TOO_LARGE,
      "blob.unsupportedContentType" to BLOB_UNSUPPORTED_CONTENT_TYPE,
      "blob.quotaExceeded" to BLOB_QUOTA_EXCEEDED,
      "rateLimit.exceeded" to RATE_LIMIT_EXCEEDED,
      "server.internal" to SERVER_INTERNAL,
    )
    fun fromWire(value: String?): FrickErrorCode? = value?.let { BY_WIRE[it] }
  }
}

/**
 * An RFC3339 timestamp carried verbatim from the wire. The canonical value
 * is [rawValue] (a fixed RFC3339 string) — an inline value class serializes
 * as that bare string, so it re-encodes byte-identically and fractional
 * seconds and the exact offset (Z vs +00:00) never drift on round-trip.
 * [instant] is a convenience that parses [rawValue]; the wire value is
 * unaffected by it, and no custom serializer configuration is required.
 */
@Serializable
@JvmInline
value class FrickTimestamp(val rawValue: String) {
  /** The parsed instant, or null if [rawValue] is not a valid RFC3339 timestamp. */
  val instant: Instant?
    get() = try {
      OffsetDateTime.parse(rawValue).toInstant()
    } catch (e: DateTimeParseException) {
      null
    }
}

data class UserDto(
  val id: String,
  val displayName: String,
  val avatarBlobId: String? = null
)

data class ConversationDto(
  val id: String,
  val kind: String,
  val title: String? = null,
  val createdBy: String,
  val lastMessageEventId: String? = null
)

data class RoomMemberDto(
  val id: String,
  val conversationId: String,
  val userId: String,
  val role: String
)

data class UserDeviceDto(
  val id: String,
  val userId: String,
  val label: String? = null,
  val platform: String,
  val lastSeenAt: FrickTimestamp? = null
)

data class UserSessionDto(
  val id: String,
  val userId: String,
  val deviceId: String,
  val replicaId: String,
  val expiresAt: FrickTimestamp
)

data class MessageDraftDto(
  val id: String,
  val userId: String,
  val conversationId: String,
  val body: String,
  val updatedAt: FrickTimestamp
)

data class ScheduledMessageDto(
  val id: String,
  val userId: String,
  val conversationId: String,
  val body: String,
  val scheduledFor: FrickTimestamp,
  val attachmentBlobIds: JsonElement? = null,
  val status: String
)

data class CallRoomDto(
  val id: String,
  val conversationId: String,
  val state: String,
  val createdBy: String,
  val kind: String,
  val createdAt: FrickTimestamp,
  val startedAt: FrickTimestamp? = null,
  val endedAt: FrickTimestamp? = null,
  val mediaSessionId: String? = null,
  val transport: String? = null
)

data class CallInviteDto(
  val id: String,
  val callId: String,
  val inviteeUserId: String,
  val status: String,
  val invitedBy: String,
  val invitedAt: FrickTimestamp,
  val respondedAt: FrickTimestamp? = null
)

data class CallParticipantDto(
  val id: String,
  val callId: String,
  val userId: String,
  val deviceId: String,
  val state: String,
  val joinedAt: FrickTimestamp,
  val leftAt: FrickTimestamp? = null,
  val micEnabled: Boolean,
  val cameraEnabled: Boolean,
  val screenSharing: Boolean
)

data class MessageSentDto(
  val messageId: String,
  val senderId: String,
  val body: String,
  val createdAt: FrickTimestamp,
  val attachmentBlobIds: JsonElement? = null
)

data class MessageEditedDto(
  val messageId: String,
  val body: String,
  val editedAt: FrickTimestamp
)

data class MessageRedactedDto(
  val messageId: String,
  val redactedAt: FrickTimestamp
)

data class ReactionAddedDto(
  val messageId: String,
  val userId: String,
  val emoji: String
)

data class ReceiptAdvancedDto(
  val userId: String,
  val sequence: Int
)

data class CallCreatedDto(
  val callId: String,
  val conversationId: String,
  val createdBy: String,
  val kind: String,
  val createdAt: FrickTimestamp
)

data class CallInviteSentDto(
  val callId: String,
  val inviteeUserId: String,
  val invitedBy: String
)

data class CallInviteAcceptedDto(
  val callId: String,
  val inviteeUserId: String
)

data class CallParticipantJoinedDto(
  val callId: String,
  val userId: String,
  val deviceId: String,
  val joinedAt: FrickTimestamp
)

data class CallParticipantMediaChangedDto(
  val callId: String,
  val userId: String,
  val deviceId: String,
  val micEnabled: Boolean,
  val cameraEnabled: Boolean,
  val screenSharing: Boolean
)

data class CallParticipantLeftDto(
  val callId: String,
  val userId: String,
  val deviceId: String,
  val leftAt: FrickTimestamp
)

data class CallEndedDto(
  val callId: String,
  val endedBy: String,
  val endedAt: FrickTimestamp
)

data class TypingStateDto(
  val isTyping: Boolean
)

data class WebRtcSignalDto(
  val senderDeviceId: String,
  val recipientDeviceId: String? = null,
  val kind: String,
  val payload: ByteArray
)
