//! Golden lint-fixture conformance: every case under
//! `conformance/fixtures/lint/manifest.json` (generated by the TypeScript
//! linter via `pnpm fixtures:lint`) must produce the exact same
//! `FrickLintResult` from the Rust linter — same ruleId strings, severities,
//! paths, messages, finding order, and breakingCount.

use frick_protocol::schema::FrickSchema;
use frick_schema::{FrickLintResult, lint_schema, lint_schema_change};
use std::collections::BTreeSet;
use std::path::PathBuf;

/// Update when the generator's case list changes — an exact count keeps a
/// shrunken regeneration from passing silently.
const EXPECTED_CASES: usize = 81;

/// Every ruleId the linter can emit; the fixture set must trigger each one
/// (mirrors the generator's own coverage assertion).
const EXPECTED_RULE_COVERAGE: usize = 53;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance/fixtures/lint")
}

fn load_manifest() -> serde_json::Value {
    let path = fixtures_dir().join("manifest.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "read {} (run `pnpm fixtures:lint` first): {err}",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("manifest parses")
}

fn schema_from(case: &serde_json::Value, name: &str, key: &str) -> FrickSchema {
    serde_json::from_value(case[key].clone())
        .unwrap_or_else(|err| panic!("{name}: deserialize {key} schema: {err}"))
}

#[test]
fn golden_lint_fixtures_match_the_typescript_linter() {
    let manifest = load_manifest();
    let cases = manifest["cases"].as_array().expect("manifest cases");
    assert_eq!(
        cases.len(),
        EXPECTED_CASES,
        "fixture case count changed — update EXPECTED_CASES"
    );

    let mut names = BTreeSet::new();
    let mut covered_rules = BTreeSet::new();

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        assert!(names.insert(name.to_owned()), "{name}: duplicate case name");

        let current = schema_from(case, name, "current");
        let result = match case["mode"].as_str().expect("case mode") {
            "schema" => {
                assert!(
                    case.get("previous").is_none(),
                    "{name}: schema-mode case carries a previous snapshot"
                );
                lint_schema(&current)
            }
            "change" => {
                let previous = schema_from(case, name, "previous");
                lint_schema_change(&current, &previous)
            }
            other => panic!("{name}: unknown mode {other}"),
        };

        // Deep, order-sensitive equality with the TS linter's JSON. Object
        // key order is insignificant in `serde_json::Value`, but the findings
        // array compares element-by-element in order.
        let actual = serde_json::to_value(&result).expect("serialize lint result");
        assert_eq!(
            actual, case["expected"],
            "{name}: Rust lint result diverged from the TS linter"
        );

        // The expected JSON must also round-trip through the typed structs
        // (pins the Deserialize side of the serde impls).
        let expected_typed: FrickLintResult = serde_json::from_value(case["expected"].clone())
            .unwrap_or_else(|err| panic!("{name}: deserialize expected result: {err}"));
        assert_eq!(
            result, expected_typed,
            "{name}: typed round-trip of the expected result diverged"
        );

        for found in &result.findings {
            covered_rules.insert(found.rule_id.clone());
        }
    }

    assert_eq!(
        covered_rules.len(),
        EXPECTED_RULE_COVERAGE,
        "rule coverage changed — update EXPECTED_RULE_COVERAGE (rules seen: {covered_rules:?})"
    );
}
