//! Golden wire-fixture conformance: every fixture under
//! `conformance/fixtures/wire/` (generated by the TypeScript encoder via
//! `pnpm fixtures:wire`) must decode, re-encode byte-identically (where the
//! manifest says `reencode: true`), and match the manifest's logical JSON
//! through both the dynamic and the typed layer.

use base64::Engine as _;
use frick_protocol::{FrickFrame, PROTOCOL_VERSION, Value, decode_frame, encode_frame};
use std::collections::BTreeSet;
use std::path::PathBuf;

/// Update when the generator's case list changes — exact counts keep a
/// shrunken regeneration from passing silently.
const EXPECTED_CASES: usize = 73;
const EXPECTED_REENCODE: usize = 70;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance/fixtures/wire")
}

fn load_manifest() -> serde_json::Value {
    let path = fixtures_dir().join("manifest.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "read {} (run `pnpm fixtures:wire` first): {err}",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("manifest parses")
}

/// Mirror of the generator's `toJsonSafe`: msgpack value → JSON with
/// `Uint8Array` as `{"$bytes": base64}`. Map-key order is not significant —
/// `serde_json::Value` object equality is order-insensitive.
fn value_to_json(value: &Value) -> serde_json::Value {
    match value {
        Value::Nil => serde_json::Value::Null,
        Value::Boolean(flag) => (*flag).into(),
        Value::Integer(int) => int
            .as_i64()
            .map(serde_json::Value::from)
            .or_else(|| int.as_u64().map(serde_json::Value::from))
            .expect("integer fits json"),
        Value::F32(float) => serde_json::Value::from(f64::from(*float)),
        Value::F64(float) => serde_json::Value::from(*float),
        Value::String(text) => text.as_str().expect("valid utf8 string").into(),
        Value::Binary(bytes) => serde_json::json!({
            "$bytes": base64::engine::general_purpose::STANDARD.encode(bytes)
        }),
        Value::Array(items) => serde_json::Value::Array(items.iter().map(value_to_json).collect()),
        Value::Map(entries) => serde_json::Value::Object(
            entries
                .iter()
                .map(|(key, entry)| {
                    (
                        key.as_str().expect("string map key").to_string(),
                        value_to_json(entry),
                    )
                })
                .collect(),
        ),
        Value::Ext(..) => panic!("fixtures never contain msgpack ext values"),
    }
}

fn frame_to_json(frame: &FrickFrame) -> serde_json::Value {
    let bytes = encode_frame(frame).expect("typed encode");
    let dynamic = rmpv::decode::read_value(&mut bytes.as_slice()).expect("re-read typed encode");
    value_to_json(&dynamic)
}

#[test]
fn golden_fixtures_decode_reencode_and_match_manifest() {
    let manifest = load_manifest();
    assert_eq!(
        manifest["protocolVersion"].as_i64(),
        Some(PROTOCOL_VERSION),
        "manifest protocolVersion diverged from PROTOCOL_VERSION"
    );

    let cases = manifest["cases"].as_array().expect("manifest cases");
    assert_eq!(
        cases.len(),
        EXPECTED_CASES,
        "fixture case count changed — update EXPECTED_CASES"
    );

    // No orphan .bin files: the directory contents must equal the manifest.
    let manifest_bins: BTreeSet<String> = cases
        .iter()
        .map(|case| case["bin"].as_str().expect("bin path").to_string())
        .collect();
    let disk_bins: BTreeSet<String> = std::fs::read_dir(fixtures_dir())
        .expect("fixtures dir")
        .map(|entry| {
            entry
                .expect("dir entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| std::path::Path::new(name).extension() == Some("bin".as_ref()))
        .collect();
    assert_eq!(
        disk_bins, manifest_bins,
        "fixture dir and manifest disagree"
    );

    let mut reencoded = 0usize;
    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let bytes = std::fs::read(fixtures_dir().join(case["bin"].as_str().expect("bin path")))
            .unwrap_or_else(|err| panic!("{name}: read bin: {err}"));

        // 1. The dynamic msgpack layer must round-trip the exact bytes —
        //    this validates width/format preservation independent of typing.
        let mut slice = bytes.as_slice();
        let dynamic = rmpv::decode::read_value(&mut slice)
            .unwrap_or_else(|err| panic!("{name}: rmpv decode: {err}"));
        assert!(slice.is_empty(), "{name}: trailing bytes after value");
        let mut dynamic_bytes = Vec::new();
        rmpv::encode::write_value(&mut dynamic_bytes, &dynamic).expect("rmpv encode");
        assert_eq!(dynamic_bytes, bytes, "{name}: rmpv re-encode diverged");

        // 2. The dynamic value must match the manifest's logical JSON.
        assert_eq!(
            value_to_json(&dynamic),
            case["json"],
            "{name}: decoded value disagrees with manifest json"
        );

        // 3. The typed layer must decode and agree on the frame kind.
        let frame: FrickFrame =
            decode_frame(&bytes).unwrap_or_else(|err| panic!("{name}: typed decode: {err}"));
        assert_eq!(
            frame.kind() as u64,
            case["kind"].as_u64().expect("kind"),
            "{name}: frame kind mismatch"
        );

        // 4. Unless the case is marked lossy, the typed decode must preserve
        //    the full logical value (catches silently-dropped fields even for
        //    cases whose byte order the typed structs don't reproduce).
        let lossy = case["lossy"].as_bool().expect("lossy flag");
        if !lossy {
            assert_eq!(
                frame_to_json(&frame),
                case["json"],
                "{name}: typed round-trip lost or changed information"
            );
        }

        // 5. Where marked, typed re-encode must be byte-identical.
        if case["reencode"].as_bool().expect("reencode flag") {
            let encoded =
                encode_frame(&frame).unwrap_or_else(|err| panic!("{name}: encode: {err}"));
            assert_eq!(
                encoded, bytes,
                "{name}: typed re-encode diverged from the TS encoder"
            );
            reencoded += 1;
        }
    }

    assert_eq!(
        reencoded, EXPECTED_REENCODE,
        "reencode count changed — update EXPECTED_REENCODE"
    );
}
